chore: hopefully fixes aws cleanup

diff --git a/ci3/aws_request_instance_type b/ci3/aws_request_instance_type
--- a/ci3/aws_request_instance_type
+++ b/ci3/aws_request_instance_type
@@ -1,37 +1,30 @@
 #!/usr/bin/env bash
-[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
-set -eu
+source $(git rev-parse --show-toplevel)/ci3/source
 
-NAME=$1
-INSTANCE_TYPE=$2
-PRICE=$3
-AMI=$4
+name=$1
+instance_type=$2
+price=$3
+ami=$4
+state_dir=$5
 
-cd $(dirname $0)
+spec_path=$state_dir/spec.json
+sir_path=$state_dir/sir
+iid_path=$state_dir/iid
+ip_path=$state_dir/ip
 
 function cleanup {
-  local code=$1
-  if [ -n "${SIR:-}" ]; then
-      >&2 echo "Cancelling spot request $SIR..."
-      aws ec2 cancel-spot-instance-requests --spot-instance-request-ids $SIR > /dev/null
-  fi
-  if [ -n "${IID:-}" ]; then
-    >&2 echo "Terminating instance $IID..."
-    aws ec2 terminate-instances --instance-ids "$IID" > /dev/null
-  fi
-  exit $code
+  aws_terminate_instance $state_dir
 }
-trap 'cleanup 130' SIGINT
-trap 'cleanup 143' SIGTERM
+trap 'cleanup' SIGINT SIGTERM
 
 export AWS_DEFAULT_REGION=us-east-2
 
 launch_spec=$(cat <<EOF
 {
-  "ImageId": "$AMI",
+  "ImageId": "$ami",
   "KeyName": "${KEY_NAME:-build-instance}",
   "SecurityGroupIds": ["sg-0ccd4e5df0dcca0c9"],
-  "InstanceType": "$INSTANCE_TYPE",
+  "InstanceType": "$instance_type",
   "BlockDeviceMappings": [
     {
       "DeviceName": "/dev/sda1",
@@ -48,72 +41,72 @@ EOF
 )
 
 # Save the launch specification to a temporary file.
-temp_file=$(mktemp)
-trap "rm -f $temp_file" EXIT
-echo "$launch_spec" > "$temp_file"
+echo "$launch_spec" > "$spec_path"
 
-info="(name: $NAME) (type: $INSTANCE_TYPE) (ami: $AMI) (bid: $PRICE)"
+info="(name: $name) (type: $instance_type) (ami: $ami) (bid: $price)"
 
 if [ "${NO_SPOT:-0}" -ne 1 ]; then
-  >&2 echo "Requesting $INSTANCE_TYPE spot instance $info..."
-  SIR=$(aws ec2 request-spot-instances \
-    --spot-price "$PRICE" \
+  >&2 echo "Requesting $instance_type spot instance $info..."
+  sir=$(aws ec2 request-spot-instances \
+    --spot-price "$price" \
     --instance-count 1 \
     --type "one-time" \
-    --launch-specification file://$temp_file \
+    --launch-specification file://$spec_path \
     --query "SpotInstanceRequests[*].[SpotInstanceRequestId]" \
     --output text)
+  echo $sir > $sir_path
 
-  >&2 echo "Waiting for instance id for spot request: $SIR..."
+  >&2 echo "Waiting for instance id for spot request: $sir..."
   sleep 5
-  for I in {1..6}; do
-    IID=$(aws ec2 describe-spot-instance-requests \
-      --spot-instance-request-ids $SIR \
+  for i in {1..6}; do
+    iid=$(aws ec2 describe-spot-instance-requests \
+      --spot-instance-request-ids $sir \
       --query "SpotInstanceRequests[*].[InstanceId]" \
       --output text)
+    [ -z "$iid" -o "$iid" == "None" ] || break
 
-    [ -z "$IID" -o "$IID" == "None" ] || break
-
-    if [ $I -eq 6 ]; then
+    if [ $i -eq 6 ]; then
       >&2 echo "Timeout waiting for spot request."
       # Cancel spot request. We may still get allocated an instance if it's *just* happened.
-      aws ec2 cancel-spot-instance-requests --spot-instance-request-ids $SIR > /dev/null
+      aws ec2 cancel-spot-instance-requests --spot-instance-request-ids $sir > /dev/null
     fi
 
     sleep 5
   done
+  echo $iid > $iid_path
 fi
 
-if [ -z "${IID:-}" -o "${IID:-}" == "None" ]; then
+if [ -z "${iid:-}" -o "${iid:-}" == "None" ]; then
   # Request on-demand instance.
-  >&2 echo "Requesting $INSTANCE_TYPE on-demand instance $info..."
-  IID=$(aws ec2 run-instances \
-    --cli-input-json file://$temp_file \
+  >&2 echo "Requesting $instance_type on-demand instance $info..."
+  iid=$(aws ec2 run-instances \
+    --cli-input-json file://$spec_path \
     --query "Instances[*].[InstanceId]" \
     --output text)
+  echo $iid > $iid_path
 fi
 
-aws ec2 create-tags --resources $IID --tags "Key=Name,Value=$NAME"
-aws ec2 create-tags --resources $IID --tags "Key=Group,Value=build-instance"
+aws ec2 create-tags --resources $iid --tags "Key=Name,Value=$name"
+aws ec2 create-tags --resources $iid --tags "Key=Group,Value=build-instance"
 
-while [ -z "${IP:-}" ]; do
+while [ -z "${ip:-}" ]; do
   sleep 1
-  IP=$(aws ec2 describe-instances \
-    --filter "Name=instance-id,Values=$IID" \
+  ip=$(aws ec2 describe-instances \
+    --filter "Name=instance-id,Values=$iid" \
     --query "Reservations[*].Instances[*].PublicIpAddress" \
     --output=text)
+  echo $ip > $ip_path
 done
 
 # Wait till ssh port is open.
->&2 echo "Waiting for SSH at $IP..."
+>&2 echo "Waiting for SSH at $ip..."
 SECONDS=0
 SSH_CONFIG_PATH=${SSH_CONFIG_PATH:-aws/build_instance_ssh_config}
 [ "${NO_TERMINATE:-0}" -eq 1 ] && LIVE_CMD=true || LIVE_CMD="sudo shutdown -h +${AWS_SHUTDOWN_TIME:-60}"
-while ! ssh -F $SSH_CONFIG_PATH -o ConnectTimeout=1 $IP $LIVE_CMD > /dev/null 2>&1; do
+while ! ssh -F $SSH_CONFIG_PATH -o ConnectTimeout=1 $ip $LIVE_CMD > /dev/null 2>&1; do
   if (( SECONDS >= 60 )); then
-    >&2 echo "Timeout: SSH could not login to $IP within 60 seconds."
+    >&2 echo "Timeout: SSH could not login to $ip within 60 seconds."
     exit 1
   fi
   sleep 1
 done
-echo $IP:${SIR:-}:$IID
