host evict tracking

diff --git a/ci3/bootstrap_ec2 b/ci3/bootstrap_ec2
--- a/ci3/bootstrap_ec2
+++ b/ci3/bootstrap_ec2
@@ -113,7 +113,7 @@ if [ -t 1 ]; then
   fi
 else
   # We're probably running in CI. Handle aws evictions and add timestamps to the logs.
-  run_cmd="ci3/aws_handle_evict run 2>&1 | ci3/add_timestamps | DUP=1 ci3/cache_log 'CI run' \$ci_log_id"
+  run_cmd="run 2>&1 | ci3/add_timestamps | DUP=1 ci3/cache_log 'CI run' \$ci_log_id"
 fi
 
 container_script=$(cat <<EOF
@@ -255,7 +255,21 @@ function run {
       -e SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-} \
       -e AWS_TOKEN=\$(curl -sX PUT http://169.254.169.254/latest/api/token -H 'X-aws-ec2-metadata-token-ttl-seconds: 21600') \
       --pids-limit=32768 \
-      aztecprotocol/devbox:3.0 bash -c $(printf '%q' "$container_script")
+      aztecprotocol/devbox:3.0 bash -c $(printf '%q' "$container_script") &
+
+    docker_pid=\$!
+    while true; do
+      if curl -fs -H "X-aws-ec2-metadata-token: $AWS_TOKEN" http://169.254.169.254/latest/meta-data/spot/termination-time &>/dev/null; then
+        # Termination notice found, exit with 155.
+        echo "Spot will be terminated! Exiting early."
+        kill \$docker_pid || true
+        exit 155
+      fi
+      sleep 1
+    done
+
+    # Returns exit code from docker run.
+    wait \$docker_pid
   "
 }
 
