Make world state fail if no napi

diff --git a/ci3/cache_download b/ci3/cache_download
--- a/ci3/cache_download
+++ b/ci3/cache_download
@@ -24,6 +24,6 @@ else
   # Default to AWS S3 URL if no custom endpoint is set
   S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
   # Attempt to download and extract the cache file
-  (curl -s -f "$S3_ENDPOINT/build-cache/$TAR_FILE" | tar -xzf - -C "$OUT_DIR" 2>/dev/null) || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
+  (curl -s -f "$S3_ENDPOINT/build-cache/$TAR_FILE" | tar -tzf - -C "$OUT_DIR") || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
 fi
 echo "Cache download and extraction of $TAR_FILE complete." >&2
