cache and bench cleanup, add e2e_ivc_bench to cpp/bootstrap.sh

diff --git a/ci3/cache_content_hash b/ci3/cache_content_hash
--- a/ci3/cache_content_hash
+++ b/ci3/cache_content_hash
@@ -44,9 +44,10 @@ diff="$({
 # Check for uncommitted files/changes.
 # Only use this check if AZTEC_CACHE_COMMIT is the default, otherwise the user is being explicit about using git history.
 if [ -n "$diff" ] && [ "$AZTEC_CACHE_COMMIT" == "HEAD" ]; then
-  # Fail. We shouldn't be writing files during the build.
+  # Fail. We shouldn't be changing files during the CI run.
   if [ "${CI:-0}" = 1 ]; then
-    echo_stderr "WARNING: Noticed changes to rebuild patterns: $diff"
+    echo_stderr "ERROR: Noticed changes to rebuild patterns: $diff"
+    exit 1
   fi
   # Signal to cache_upload and cache_download to not touch this file.
   echo "disabled-cache"
