be strict

diff --git a/ci3/cache_content_hash b/ci3/cache_content_hash
--- a/ci3/cache_content_hash
+++ b/ci3/cache_content_hash
@@ -45,6 +45,11 @@ diff="$({
 
 # Check for uncommitted files/changes
 if [ -n "$diff" ]; then
+  # Fail. We shouldn't be writing files during the build.
+  if [ "${CI:-0}" = 1 ]; then
+    echo "Noticed changes to rebuild patterns: "$@", would disable cache but being strict because CI=1. The diff: $diff"
+    exit 1
+  fi
   # Signal to cache_upload and cache_download to not touch this file.
   echo "disabled-cache"
   exit 0
