wip

diff --git a/ci3/run_test_cmd b/ci3/run_test_cmd
--- a/ci3/run_test_cmd
+++ b/ci3/run_test_cmd
@@ -10,7 +10,9 @@ cmd=$1
 export test_cmd="${cmd#* }"
 key=$(hash_str_orig "$cmd")
 
-if [ "${USE_TEST_CACHE:-0}" -eq 1 ] && [ "$CI_REDIS_AVAILABLE" -eq 1 ]; then
+# We can skip the test if it's already been successfully run.
+# We actually pre-filter tests in CI runs so this is rarely hit.
+if [ "$USE_TEST_CACHE" -eq 1 ]; then
   log_key=$(redis_cli GET $key)
   if [ -n "$log_key" ]; then
     log_info=" (${yellow}http://ci.aztec-labs.com/$log_key${reset})"
@@ -25,9 +27,8 @@ export VERBOSE=1
 # Run the test, capturing output, with a timeout of 10m.
 # We cannot use "output=$(timeout ...)" here as it stymies proper signal propagation.
 # To ensure we can propagate SIGTERM to timeouts process group we use a temp file and forward the signal.
-set +e
 tmp_file=/tmp/$key
-
+# Print test metadata header.
 cat <<EOF >$tmp_file
 Command: $cmd
 Commit: https://github.com/AztecProtocol/aztec-packages/commit/$COMMIT_HASH
@@ -35,8 +36,11 @@ Env: REF_NAME=$REF_NAME CURRENT_VERSION=$CURRENT_VERSION CI_FULL=$CI_FULL
 Date: $(date)
 
 EOF
-
+# Remove the tmp fail on exit.
 trap "rm -f $tmp_file" EXIT
+
+# Run the test. Disable exit on error. Handle timeout override in the test_cmd.
+set +e
 if [[ "$test_cmd" = timeout* ]]; then
   bash -c "set -euo pipefail; $test_cmd 2>&1 | add_timestamps" &>> $tmp_file &
 else
@@ -50,54 +54,71 @@ code=$?
 if [ "$CI_REDIS_AVAILABLE" -eq 1 ]; then
   log_key=$(uuid)
 
-  if [ $code -eq 0 ]; then
-    # Set success flag for test. This key is unique to the test.
+  # If the test succeeded and we're using the test cache, set success flag for test. This key is unique to the test.
+  if [ $code -eq 0 ] && [ "$USE_TEST_CACHE" -eq 1 ]; then
     redis_cli SETEX $key 604800 $log_key &>/dev/null
   fi
 
-  # Set the test log. This key is globally unique.
-  cat $tmp_file | redis_setexz $log_key $CI_REDIS_EXPIRE
-  log_info=" (${yellow}http://ci.aztec-labs.com/$log_key${reset})"
-fi
-
-if [ $code -eq 0 ]; then
-  echo -e "${green}PASSED${reset}${log_info:-}: $test_cmd (${SECONDS}s)"
-else
-  # Send slack message to owners.
-  owners=$(yq e -r '.tests[] | .regex as $pattern | select(strenv(test_cmd) | test($pattern)) | .owners[]' .test_patterns.yml | sort -u)
-
-  # To not fail a test, we at least need an owner to notify.
-  if [ -z "$owners" ]; then
-    # No owner, fail.
-    tag="${red}FAILED${reset}"
-    exit_code=$code
-  else
-    # We will not fail a FLAKED test as we slack info to the owner.
-    tag="${purple}FLAKED${reset}"
-
-    slack_users=$(curl -s -X GET https://slack.com/api/users.list -H "Authorization: Bearer $SLACK_BOT_TOKEN")
-    slack_uids=""
-    for email in $owners; do
-      uid=$(echo "$slack_users" | jq -r --arg email "$email" '.members[] | select(.profile.email == $email) | .id')
-      [ -n "$uid" ] && slack_uids+="<@$uid> "
-    done
-    read -r -d '' data <<EOF
-{
-  "channel": "#aztec3-ci",
-  "text": "${slack_uids}: Test flaked \`$test_cmd\` http://ci.aztec-labs.com/$log_key"
-}
-EOF
-    curl -X POST https://slack.com/api/chat.postMessage \
-      -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
-      -H "Content-type: application/json" \
-      --data "$data" &>/dev/null
-
-    exit_code=0
+  # If the test failed OR it succeeded and we're running in CI, save the test log.
+  # It's not worth spamming redis for local runs of tests that succeed.
+  if [ $code -ne 0 ] || [ "${CI:-0}" -eq 1 ]; then
+    # Set the test log. This key is globally unique.
+    cat $tmp_file | redis_setexz $log_key $CI_REDIS_EXPIRE
+    log_info=" (${yellow}http://ci.aztec-labs.com/$log_key${reset})"
   fi
-
-  echo -e "${tag}${reset}${log_info:-}: $test_cmd (${SECONDS}s) (code: $code)"
-  cat $tmp_file
-  echo -e "${tag}${reset}${log_info:-}: $test_cmd (${SECONDS}s) (code: $code)"
 fi
 
-exit $exit_code
+# Show PASSED and early out on success.
+function pass {
+  echo -e "${green}PASSED${reset}${log_info:-}: $test_cmd (${SECONDS}s)"
+  exit
+}
+
+# Show FAILED and exit with error code.
+function fail {
+  echo -e "${red}FAILED${reset}${log_info:-}: $test_cmd (${SECONDS}s) (code: $code)"
+  cat $tmp_file
+  echo -e "${red}FAILED${reset}${log_info:-}: $test_cmd (${SECONDS}s) (code: $code)"
+  exit $code
+}
+
+# Show FLAKED and send slack message to test owner(s). Exit with success.
+function flake {
+  echo -e "${purple}FLAKED${reset}${log_info:-}: $test_cmd (${SECONDS}s) (code: $code)"
+
+  # Send slack message to owners.
+  slack_users=$(curl -s -X GET https://slack.com/api/users.list -H "Authorization: Bearer $SLACK_BOT_TOKEN")
+  slack_uids=""
+  for email in $owners; do
+    uid=$(echo "$slack_users" | jq -r --arg email "$email" '.members[] | select(.profile.email == $email) | .id')
+    [ -n "$uid" ] && slack_uids+="<@$uid> "
+  done
+  read -r -d '' data <<EOF
+  {
+    "channel": "#aztec3-ci",
+    "text": "${slack_uids}: Test flaked \`$test_cmd\` http://ci.aztec-labs.com/$log_key"
+  }
+EOF
+  curl -X POST https://slack.com/api/chat.postMessage \
+    -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
+    -H "Content-type: application/json" \
+    --data "$data" &>/dev/null
+
+  exit
+}
+
+# Test passed.
+[ $code -eq 0 ] && pass
+
+# We're not in CI, fail.
+[ "$CI" -eq 0 ] && fail
+
+# Get list of owners of this failed test.
+owners=$(yq e -r '.tests[] | .regex as $pattern | select(strenv(test_cmd) | test($pattern)) | .owners[]' .test_patterns.yml | sort -u)
+
+# To not fail a test, we at least need an owner to notify.
+if [ -z "$owners" ]; then
+  fail
+else
+  flake
+fi
