msan allow test timeout

diff --git a/barretenberg/cpp/Earthfile b/barretenberg/cpp/Earthfile
--- a/barretenberg/cpp/Earthfile
+++ b/barretenberg/cpp/Earthfile
@@ -64,9 +64,11 @@ preset-msan-check:
     # cmake source
     COPY --dir cmake CMakeLists.txt CMakePresets.json .
 
-    RUN cmake --preset msan -Bbuild && cmake --build build --target client_ivc_tests
+    # We never fail this as test-listing targets can timeout. Just pragmatically go on to see if the binary exists.
+    RUN cmake --preset msan -Bbuild && cmake --build build --target client_ivc_tests || true
     # install SRS needed for proving
     COPY --dir ./srs_db/+build/. srs_db
+    RUN echo "Warning: If ./bin/client_ivc_tests is not found, there may be build failures above."
     RUN cd build && ./bin/client_ivc_tests --gtest_also_run_disabled_tests
 
 preset-wasm:
