more tries

diff --git a/.github/ensure-tester/action.yml b/.github/ensure-tester/action.yml
--- a/.github/ensure-tester/action.yml
+++ b/.github/ensure-tester/action.yml
@@ -70,7 +70,7 @@ runs:
 
     - name: Print Startup Log
       shell: bash
-      run: scripts/run_on_tester "cat /run/log.out" || true # don't fail
+      run: scripts/run_on_tester "cat /home/ubuntu/.user-data-finished ; cat /run/log.out" || true # don't fail
 
     # Set up a context for this run
     - name: Copy Repo to Tester
