Update action.yml

diff --git a/.github/ensure-tester/action.yml b/.github/ensure-tester/action.yml
--- a/.github/ensure-tester/action.yml
+++ b/.github/ensure-tester/action.yml
@@ -70,7 +70,7 @@ runs:
 
     - name: Print Startup Log
       shell: bash
-      run: cat /run/log.out
+      run: cat /run/log.out || true # don't fail
 
     # Set up a context for this run
     - name: Copy Repo to Tester
