fix

diff --git a/.github/ensure-tester/action.yml b/.github/ensure-tester/action.yml
--- a/.github/ensure-tester/action.yml
+++ b/.github/ensure-tester/action.yml
@@ -92,35 +92,6 @@ runs:
             git fetch --depth 1 origin $GIT_COMMIT
             git checkout FETCH_HEAD >/dev/null
           )
-      shell: bash
-      run: |
-        scripts/run_on_tester "sudo shutdown -P ${{ steps.select_instance.outputs.ttl }}; flock /var/lock/git.lock bash -c '$UNPACK'"
-        scripts/run_on_tester "
-          mkdir -p ~/.ssh
-          echo $BUILD_INSTANCE_SSH_KEY | base64 --decode > ~/.ssh/build_instance_key
-          chmod 600 ~/.ssh/build_instance_key
-          i=0
-          while ! systemctl is-active --quiet docker; do
-            sleep 2
-            if [ $(( i++ )) -gt 60 ]; then
-              echo "Docker service not found! Report this."
-              exit 1
-            fi
-          done
-          echo "Docker service is active!"
-          echo $DOCKERHUB_PASSWORD | docker login -u aztecprotocolci --password-stdin
-        "
-
-    - name: Setup yq and earthly
-      uses: ./.github/run-on-tester
-      with:
-        run: |
-          wget https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -O ./yq 2>&1 >/dev/null
-          chmod +x ./yq
-          DENOISE=1 ci3/denoise sudo mv ./yq /usr/bin/yq
-          ci3/earthly_install
-          echo "Waiting for Docker service to become active..."
-          i=0
 
     - name: Ensure Tester Cleanup
       uses: gacts/run-and-post-run@v1
@@ -131,7 +102,41 @@ runs:
       id: test
       env:
         RUN_SCRIPT: |
-          cd ~/run-${{ env.RUN_ID }};
+          set -eux
+          sudo shutdown -P ${{ steps.select_instance.outputs.ttl }}
+          # Clone repo.
+          [ -d ~/run-$RUN_ID ] || (
+            mkdir -p ~/run-$RUN_ID
+            cd ~/run-$RUN_ID
+            git init &>/dev/null
+            git remote add origin https://github.com/aztecprotocol/aztec-packages
+            git fetch --depth 1 origin $GIT_COMMIT
+            git checkout FETCH_HEAD >/dev/null
+          )
+          cd ~/run-${{ env.RUN_ID }}
+          # One-time config.
+          mkdir -p ~/.ssh
+          echo $BUILD_INSTANCE_SSH_KEY | base64 --decode > ~/.ssh/build_instance_key
+          chmod 600 ~/.ssh/build_instance_key
+          set +x
+          # Ensure docker is active.
+          echo "Waiting for Docker service to become active..."
+          i=0
+          while ! systemctl is-active --quiet docker; do
+            sleep 2
+            if [ $(( i++ )) -gt 60 ]; then
+              echo "Docker service not found! Report this."
+              exit 1
+            fi
+          done
+          echo "Docker service is active!"
+          echo $DOCKERHUB_PASSWORD | docker login -u aztecprotocolci --password-stdin
+          # Install yq and earthly.
+          wget https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -O ./yq 2>&1 >/dev/null
+          ci3/earthly_install
+          chmod +x ./yq
+          sudo mv ./yq /usr/bin/yq
+          # Run command.
           ci3/aws_handle_evict "set -eu; ${{ inputs.run }}"
       shell: bash
       run:
