initial

diff --git a/aztec-up/bin/aztec-install b/aztec-up/bin/aztec-install
--- a/aztec-up/bin/aztec-install
+++ b/aztec-up/bin/aztec-install
@@ -9,8 +9,6 @@ p="\033[35m" # Purple
 r="\033[0m"  # Reset
 bold="\033[1m"
 
-export DOCKER_CLI_HINTS=false
-
 if [ ! -t 0 ]; then
   NON_INTERACTIVE=1
 else
@@ -21,10 +19,13 @@ AZTEC_PATH="${AZTEC_PATH:-$HOME/.aztec}"
 BIN_PATH=${BIN_PATH:-$AZTEC_PATH/bin}
 
 # Define version if specified, otherwise set to "latest".
+# For testing you can override the INSTALL_URI to point to a file uri e.g. file:///home/user/aztec-packages/aztec-up/bin
 VERSION=${VERSION:-"latest"}
-INSTALL_URI=${INSTALL_URI:-https://install.aztec.network}
-if [ "$VERSION" != "latest" ]; then
-  INSTALL_URI+="/$VERSION"
+if [ -z "$INSTALL_URI" ]; then
+  INSTALL_URI=https://install.aztec.network
+  if [ "$VERSION" != "latest" ]; then
+    INSTALL_URI+="/$VERSION"
+  fi
 fi
 
 # Add color to the AZTEC ascii art.
@@ -36,6 +37,7 @@ function print_colored() {
 }
 
 function title() {
+  clear
   echo
   print_colored " █████╗ ███████╗████████╗███████╗ ██████╗"
   print_colored "██╔══██╗╚══███╔╝╚══██╔══╝██╔════╝██╔════╝"
@@ -45,22 +47,13 @@ function title() {
   print_colored "╚═╝  ╚═╝╚══════╝   ╚═╝   ╚══════╝ ╚═════╝"
   echo -e "${r}"
   echo -e "Welcome to the ${bold}${b}Aztec${r} installer! Your journey into blockchain privacy begins... ${bold}${p}now${r}."
-  echo -e "We provide a docker image that works on any modern system (specifically: x64 or ARM64)."
-  echo -e "Please ensure docker is installed for your platform: https://docs.docker.com/engine/install"
   echo
-  if [ "$(uname -s)" == "Darwin" ]; then
-    echo -e "${y}WARNING: For best performance we recommend adjusting your default docker settings:"
-    echo -e "         - Under general, enable VirtioFS."
-    echo -e "         - Under resources, set CPUs to ~80% your maximum."
-    echo -e "         - Under resources, set Memory to ~80% your maximum."
-    echo -e "You may receive a warning about your home directory being mounted into a container."
-    echo -e "This is requested so we can read and write project files, that is all."
-    echo -e "${r}"
-  fi
-  echo -e "This will install the following scripts and update your PATH if necessary:"
-  echo -e "  ${bold}${g}aztec${r}                      - a collection of tools to compile and test contracts, to launch subsystems and interact with the aztec network."
-  echo -e "  ${bold}${g}aztec-up${r}                   - a tool to upgrade the aztec toolchain to the latest, or specific versions."
-  echo -e "  ${bold}${g}aztec-wallet${r}               - our minimalistic CLI wallet"
+  echo -e "This install script will install the following and update your PATH if necessary:"
+  echo -e "  ${bold}${g}noir${r}         - the version of the noir programming language compatible with this version of aztec."
+  echo -e "  ${bold}${g}bb${r}           - the version of the barretenberg proving backend compatible with this version of aztec."
+  echo -e "  ${bold}${g}aztec${r}        - a collection of tools to compile and test contracts, to launch subsystems and interact with the aztec network."
+  echo -e "  ${bold}${g}aztec-up${r}     - a tool to upgrade the aztec toolchain to the latest, or specific versions."
+  echo -e "  ${bold}${g}aztec-wallet${r} - our minimalistic CLI wallet"
   echo
   read -p "Do you wish to continue? (y/n)" -n 1 -r
   echo
@@ -69,14 +62,54 @@ function title() {
   fi
 }
 
-# Print text in green.
-function info {
+function echo_green {
   echo -e "${g}$1${r}"
 }
 
-# Print text in yellow.
-function warn {
+function echo_yellow {
   echo -e "${y}$1${r}"
+}
+
+function echo_purple {
+  echo -e "${p}$1${r}"
+}
+
+function dump_fail {
+  output=$(mktemp)
+  trap "rm $output" EXIT
+
+  $1 &>$output
+  status=$?
+
+  # 0 or SIGTERM considered a success.
+  if [ "$status" -ne 0 ] && [ "$status" -ne 143 ]; then
+    {
+      echo
+      echo -e "${red}command failed${reset}: $1 (exit: $status)"
+      echo -e "${blue}--- output ---${reset}"
+      cat $output
+    } >&2
+  fi
+
+  return $status
+}
+
+function check_toolchains {
+  # Check Node.js version.
+  local versions=$(curl -fsSL "$INSTALL_URI/versions")
+  local node_min_version=$(echo "$versions" | grep node | cut -d' ' -f2)
+  local node_installed_version=$(node --version | cut -d 'v' -f 2 || echo "none")
+  if [[ "$(printf '%s\n' "$node_min_version" "$node_installed_version" | sort -V | head -n1)" != "$node_min_version" ]]; then
+    echo "Minimum Node.js version $node_min_version not found (got $node_installed_version)."
+    echo "Installation: nvm install $node_min_version"
+    exit 1
+  fi
+}
+
+function install_file {
+  local dest="$AZTEC_PATH/$1"
+  curl -fsSL "$INSTALL_URI/$1" -o "$dest"
+  echo "Installed: $dest"
 }
 
 # Copy a file from the install source path to the bin path and make it executable.
@@ -110,11 +143,11 @@ function update_path_env_var {
 
     if [ "$NON_INTERACTIVE" -eq 0 ]; then
       # Inform the user about the change and ask for confirmation
-      warn "The directory $TARGET_DIR is not in your PATH."
+      echo_yellow "The directory $TARGET_DIR is not in your PATH."
       read -p "Add it to $SHELL_PROFILE to make the aztec binaries accessible? (y/n)" -n 1 -r
       echo
       if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-        warn "Skipped updating PATH. You might need to add $TARGET_DIR to your PATH manually to use the binary."
+        echo_yellow "Skipped updating PATH. You might need to add $TARGET_DIR to your PATH manually to use the binary."
         return
       fi
     fi
@@ -129,39 +162,96 @@ function update_path_env_var {
   fi
 }
 
-# Show title if we're in a terminal.
-[ "$NON_INTERACTIVE" -eq 0 ] && title
+function install_jq {
+  set -euo pipefail
+  url_base="https://github.com/jqlang/jq/releases/download/jq-1.8.1"
+  arch="$(uname -m)"
+  os="$(uname -s)"
 
-# Check if Docker is available.
-if ! command -v docker &>/dev/null; then
-  warn "Docker is not installed. Please install Docker and try again."
-  exit 1
-fi
+  case "$os" in
+    Linux)
+      case "$arch" in
+        x86_64|amd64) bin="jq-linux-amd64" ;;
+        aarch64|arm64) bin="jq-linux-arm64" ;;
+        *) echo "unsupported arch"; return 1 ;;
+      esac
+      ;;
+    Darwin)
+      case "$arch" in
+        x86_64|amd64) bin="jq-macos-amd64" ;;
+        aarch64|arm64) bin="jq-macos-arm64" ;;
+        *) echo "unsupported arch"; return 1 ;;
+      esac
+      ;;
+    *)
+      echo "unsupported OS"
+      return 1
+      ;;
+  esac
 
-# Check if Docker is running.
-if ! docker info &>/dev/null; then
-  warn "Docker is not running. Please start Docker and try again."
-  exit 1
-fi
+  curl -Ls "$url_base/$bin" -o $BIN_PATH/jq || return 1
+  chmod +x $BIN_PATH/jq
+}
 
-mkdir -p "$AZTEC_PATH"
-TMP_VERSION_FILE="$(mktemp)"
-echo "$VERSION" > "$TMP_VERSION_FILE"
+function install_aztec_up {
+  set -euo pipefail
+  rm -rf $BIN_PATH && mkdir -p $BIN_PATH
+  install_bin aztec-up
+  install_file versions
+  echo "$VERSION" > $AZTEC_PATH/default_version
+  update_path_env_var $BIN_PATH
+}
 
-# Pull the aztec container.
-if [ -z "${SKIP_PULL:-}" ]; then
-  info "Pulling aztec version $VERSION..."
-  docker pull aztecprotocol/aztec:$VERSION
-fi
+function install_noir {
+  set -euo pipefail
+  curl -Ls https://raw.githubusercontent.com/noir-lang/noirup/refs/heads/main/install | bash
+  $HOME/.nargo/bin/noirup -v $(cat $AZTEC_PATH/versions | grep noir | cut -d' ' -f2)
+}
 
-info "Installing scripts in $BIN_PATH..."
-rm -rf $BIN_PATH && mkdir -p $BIN_PATH
-install_bin .aztec-run
-install_bin aztec
-install_bin aztec-up
-install_bin aztec-wallet
-mv "$TMP_VERSION_FILE" "$AZTEC_PATH/default_version"
+function install_foundry {
+  set -euo pipefail
+  curl -L https://foundry.paradigm.xyz | bash
+  $HOME/.foundry/bin/foundryup -i $(cat $AZTEC_PATH/versions | grep foundry | cut -d' ' -f2)
+}
 
-update_path_env_var $BIN_PATH
+function install_aztec_packages {
+  set -euo pipefail
+  npm i -g @aztec/aztec@$VERSION @aztec/cli-wallet@$VERSION @aztec/bb.js@$VERSION
+}
 
-info "Done!"
+export -f install_aztec_up install_noir install_foundry install_aztec_packages
+
+function main {
+  # Show title if we're in a terminal.
+  [ "$NON_INTERACTIVE" -eq 0 ] && title
+
+  echo
+  check_toolchains
+
+  # Install aztec-up
+  echo -n "Installing aztec-up... "
+  dump_fail install_aztec_up
+  echo_green "done."
+
+  # Install jq
+  echo -n "Installing jq... "
+  dump_fail install_jq
+  echo_green "done."
+
+  # Install noir
+  echo -n "Installing noir... "
+  dump_fail install_noir
+  echo_green "done."
+
+  # Install foundry
+  echo -n "Installing foundry... "
+  dump_fail install_foundry
+  echo_green "done."
+
+  # Install aztec
+  echo -n "Installing aztec packages... "
+  dump_fail install_aztec_packages
+  echo_green "done."
+}
+
+main
