fix: apply review comments
update: readme

minor fix

diff --git a/circuits/cpp/scripts/run_coverage b/circuits/cpp/scripts/run_coverage
--- a/circuits/cpp/scripts/run_coverage
+++ b/circuits/cpp/scripts/run_coverage
@@ -27,52 +27,50 @@ TESTS=$1
 BUILD_DIR="build-coverage"
 
 # If the clean file is set, wipe all existing coverage data
-if [[ -n "$CLEAN" ]]; then
+if [ -n "$CLEAN" ]; then
   echo "The CLEAN environment variable is set. Clearing existing coverage data."
   rm -rf ./$BUILD_DIR || true
 fi
 
 # Perform coverage build
 echo "Setting cmake to run with preset coverage"
-cmake -Bbuild-coverage -DCMAKE_BUILD_TYPE=Debug -DUSE_TURBO=true --preset=coverage .
+cmake -DUSE_TURBO=true --preset=coverage .
 
 # if TESTS is GLOB or empty, run all built tests
 # if TESTS is a file, assume it contains a list of tests to run
 # otherwise assume TESTS itself is a list of tests to run
-if [ "$TESTS" == "glob" ] || [ -z "$TESTS" ]; then
+if [ "$TESTS" = "glob" ] || [ -z "$TESTS" ]; then
   echo "    No test file specified. Building all test files."
   TESTS=$(cat ./scripts/a3-tests)
 elif [ -f "$TESTS" ]; then
   TESTS=$(cat $TESTS | tr '\n' ' ')
 fi
 
-cd $BUILD_DIR
-
 # if just the CLEAR_COV env var is set then we will clear existing coveage report information
-if [[ -n "$CLEAR_COV" ]]; then
+if [ -n "$CLEAR_COV" ]; then
   echo "The CLEAR_COV environment variable is set. Clearing existing coverage data."
-  rm ./lcov.info || true
-  rm ./merged_profdata/default.profdata || true
-  rm ./default.profraw || true
-  rm -rf ./bin/profdata || true
+  rm ./$BUILD_DIR/lcov.info || true
+  rm ./$BUILD_DIR/merged_profdata/default.profdata || true
+  rm ./$BUILD_DIR/default.profraw || true
+  rm -rf ./$BUILD_DIR/bin/profdata || true
 fi
 
 for BIN in $TESTS; do
   echo "*** Building $BIN ***"
-  cmake --build . --target $BIN
+  cmake --build --preset coverage --target $BIN
 done
 
 echo "Testing $BIN"
 echo "*** Collecting Profiling Information ***"
-ctest || true
+ctest --test-dir $BUILD_DIR || true # Ctest will fail here if there are unbuilt tests, but we would like to continue to generate reports
 echo "Completed profiling"
 
 echo "*** Generating Coverage Reports ***"
-cmake --build . --target create_full_coverage_report
+cmake --build --preset coverage --target create_full_coverage_report
 
 echo "*** Generating VScode line coverage data ***"
 for BIN in $TESTS; do
   echo "Generating line coverage data for $BIN"
-  llvm-cov-15 export ./bin/$BIN  --format=lcov -instr-profile="./merged_profdata/default.profdata" > lcov.info
+  llvm-cov-15 export ./$BUILD_DIR/bin/$BIN  --format=lcov -instr-profile="./$BUILD_DIR/merged_profdata/default.profdata" > $BUILD_DIR/lcov.info
 done
 
