verifier deploy fix

diff --git a/spartan/aztec-network/templates/deploy-l1-verifier.yaml b/spartan/aztec-network/templates/deploy-l1-verifier.yaml
--- a/spartan/aztec-network/templates/deploy-l1-verifier.yaml
+++ b/spartan/aztec-network/templates/deploy-l1-verifier.yaml
@@ -51,19 +51,20 @@ spec:
                 sleep 5
               done
               echo "Boot node is ready!"
-
-              export ROLLUP_CONTRACT_ADDRESS=$(curl -X POST -H 'Content-Type: application/json' \
-                  -d '{"jsonrpc":"2.0","method":"node_getL1ContractAddresses","params":[],"id":1}' \
-                  "$BOOT_NODE_HOST" \
-                  | jq -r '.result.rollupAddress.value')
-
-              echo "Rollup contract address: $ROLLUP_CONTRACT_ADDRESS"
               MAX_RETRIES=5
               RETRY_DELAY=60
               for attempt in $(seq 1 $MAX_RETRIES); do
-                node /usr/src/yarn-project/aztec/dest/bin/index.js deploy-l1-verifier --verifier real
-                echo "Attempt $attempt failed. Retrying in $RETRY_DELAY seconds..."
-                sleep "$RETRY_DELAY"
+                export ROLLUP_CONTRACT_ADDRESS=$(curl -X POST -H 'Content-Type: application/json' \
+                    -d '{"jsonrpc":"2.0","method":"node_getL1ContractAddresses","params":[],"id":1}' \
+                    "$BOOT_NODE_HOST" \
+                    | jq -r '.result.rollupAddress.value' || true)
+
+                if [ -n "$ROLLUP_CONTRACT_ADDRESS" ]; then
+                  echo "Rollup contract address: $ROLLUP_CONTRACT_ADDRESS"
+                  node /usr/src/yarn-project/aztec/dest/bin/index.js deploy-l1-verifier --verifier real
+                  echo "Attempt $attempt failed. Retrying in $RETRY_DELAY seconds..."
+                  sleep "$RETRY_DELAY"
+                fi
               done || { echo "All L1 verifier deploy attempts failed." >&2; exit 1; }
               echo "L1 verifier deployed"
           env:
