retries

diff --git a/spartan/aztec-network/templates/deploy-l1-verifier.yaml b/spartan/aztec-network/templates/deploy-l1-verifier.yaml
--- a/spartan/aztec-network/templates/deploy-l1-verifier.yaml
+++ b/spartan/aztec-network/templates/deploy-l1-verifier.yaml
@@ -57,8 +57,8 @@ spec:
                   "$BOOT_NODE_HOST")
               echo "L1 Contracts"
               echo $l1_contracts
-              export ROLLUP_CONTRACT_ADDRESS=$(cat $l1_contracts | jq -r '.result.rollupAddress')
-              [ -z "$ROLLUP_CONTRACT_ADDRESS" ] && echo "Could not retrieve rollup address!" exit 1
+              export ROLLUP_CONTRACT_ADDRESS=$(echo $l1_contracts | jq -r '.result.rollupAddress')
+              [ -z "$ROLLUP_CONTRACT_ADDRESS" ] && echo "Could not retrieve rollup address!" && exit 1
               echo "Rollup contract address: $ROLLUP_CONTRACT_ADDRESS"
               MAX_RETRIES=5
               RETRY_DELAY=60
