feat: update node chart (#13951)
Co-authored-by: Maddiaa0 <47148561+Maddiaa0@users.noreply.github.com>

diff --git a/spartan/aztec-node/templates/statefulset.yaml b/spartan/aztec-node/templates/statefulset.yaml
--- a/spartan/aztec-node/templates/statefulset.yaml
+++ b/spartan/aztec-node/templates/statefulset.yaml
@@ -20,11 +20,10 @@ spec:
         {{- include "chart.selectorLabels" . | nindent 8 }}
         app: node
     spec:
-      dnsPolicy: ClusterFirst
+      serviceAccountName: {{ include "chart.serviceAccountName" . }}
+      dnsPolicy: ClusterFirstWithHostNet
+      hostNetwork: {{ .Values.hostNetwork }}
       affinity:
-        # If we are using the node port option, we need to make sure not to schedule two validators on the same node
-        # TODO(md): in future, this is only required if we run all with the same ports, and can potentially be relaxed
-        {{- if .Values.service.p2p.nodePortEnabled }}
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
@@ -35,42 +34,92 @@ spec:
                       - node
               topologyKey: kubernetes.io/hostname
               namespaceSelector: {}
-        {{- end }}
       initContainers:
       {{- if .Values.initContainers }}
         {{- tpl (toYaml .Values.initContainers | nindent 8) $ }}
       {{- end }}
-      {{- if .Values.nodePortEnabled }}
+      {{- if or .Values.service.p2p.nodePortEnabled .Values.hostNetwork }}
         - name: init-nodeport
           image: bitnami/kubectl
+          securityContext:
+            runAsNonRoot: false
+            runAsUser: 0
           command:
             - sh
             - -c
             - >
-              export EXTERNAL_PORT=$(kubectl get services -l "pod in (${POD_NAME}), type in (p2p)" -o jsonpath='{.items[0].spec.ports[0].nodePort}');
-              export EXTERNAL_IP=$(kubectl get nodes "${NODE_NAME}" -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}');
+              export POD_INDEX=$(echo ${POD_NAME} | awk -F'-' '{print $NF}');
+
+              # If running host network, we don't need to get the node port from the service
+              {{- if not .Values.hostNetwork }}
+              export EXTERNAL_PORT=$(kubectl get services -l "pod-index in (${POD_INDEX}), type in (p2p)" -o jsonpath='{.items[0].spec.ports[0].nodePort}');
               echo "export EXTERNAL_PORT=$EXTERNAL_PORT" >  /env/init-nodeport;
+              echo "export P2P_PORT=$EXTERNAL_PORT"     >> /env/init-nodeport;
+              {{- end }}
+
+              # Get the external IP of the node
+              export EXTERNAL_IP=$(kubectl get nodes "${NODE_NAME}" -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}');
+
               echo "export EXTERNAL_IP=$EXTERNAL_IP"     >> /env/init-nodeport;
               echo "export P2P_IP=$EXTERNAL_IP"         >> /env/init-nodeport;
-              echo "export P2P_PORT=$EXTERNAL_PORT"     >> /env/init-nodeport;
               cat /env/init-nodeport;
+          env:
+            - name: POD_NAME
+              valueFrom:
+                fieldRef:
+                  fieldPath: metadata.name
+            - name: NODE_NAME
+              valueFrom:
+                fieldRef:
+                  fieldPath: spec.nodeName
+          volumeMounts:
+            - name: init-nodeport
+              mountPath: /env
       {{- end }}
-
       containers:
         - name: node
-          image: {{ .Values.image }}
+          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
+          imagePullPolicy: {{ .Values.image.pullPolicy }}
           command:
             - /bin/bash
             - -c
-            - >
-              {{- if .Values.nodePortEnabled }}
+            - |
+              {{- if or .Values.service.p2p.nodePortEnabled .Values.hostNetwork }}
               source /env/init-nodeport;
+              {{- else }}
+              export P2P_IP=$(hostname -i)
               {{- end }}
 
-              node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --node --archiver
-              {{- range .Values.node.extraArgs }}
-                {{ tpl . $ }}
+              start_cmd=("node" "/usr/src/yarn-project/aztec/dest/bin/index.js" "start")
+              pod_index=$(echo $K8S_POD_NAME | awk -F'-' '{print $NF}')
+
+              {{- if or (has "--sequencer" .Values.node.startCmd) (has "--prover-node" .Values.node.startCmd) }}
+              if [[ -f /config/l1-publisher/mnemonic ]]; then
+                mnemonic=$(cat /config/l1-publisher/mnemonic)
+                mnemonic_start_index=$(cat /config/l1-publisher/mnemonicStartIndex)
+
+
+                export L1_PUBLISHER_KEY=$(cast wallet private-key --mnemonic "$mnemonic" --mnemonic-index $(($mnemonic_start_index + $pod_index)))
+                export VALIDATOR_PRIVATE_KEY=$L1_PUBLISHER_KEY
+                export SEQ_PUBLISHER_PRIVATE_KEY=$L1_PUBLISHER_KEY
+
+              elif [[ -f /config/l1-publisher/privateKeys ]]; then
+                line_index=$(($pod_index + 1))
+                export L1_PUBLISHER_KEY=$(sed -n -e "${line_index}p;${line_index}q" /config/l1-publisher/privateKeys)
+
+                if [[ -z $L1_PUBLISHER_KEY ]]; then
+                  echo "Private key for pod $K8S_POD_NAME not found"
+                  exit 1
+                fi
+
+              else
+                echo "No mnemonic or private keys configured."
+                exit 1
+              fi
               {{- end }}
+
+              start_cmd+=({{ join " " .Values.node.startCmd }})
+              "${start_cmd[@]}"
           startupProbe:
             httpGet:
               path: /status
@@ -86,12 +135,15 @@ spec:
             timeoutSeconds: 30
             failureThreshold: 3
           volumeMounts:
-            - name: node-data
+            - name: storage
               mountPath: {{ .Values.node.storage.dataDirectory }}
-            {{- if .Values.nodePortEnabled }}
+            {{- if or .Values.service.p2p.nodePortEnabled .Values.hostNetwork }}
             - name: init-nodeport
               mountPath: /env
             {{- end }}
+            - name: l1-publisher
+              mountPath: /config/l1-publisher
+              readOnly: true
           env:
             - name: POD_IP
               valueFrom:
@@ -111,10 +163,21 @@ spec:
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.namespace
+            {{- if .Values.network }}
             - name: NETWORK
-              value: "{{ .Values.network.name }}"
+              value: "{{ .Values.network }}"
+            {{- else }}
+            - name: REGISTRY_CONTRACT_ADDRESS
+              value: "{{ .Values.customNetwork.registryContractAddress }}"
+            - name: L1_CHAIN_ID
+              value: "{{ .Values.customNetwork.l1ChainId }}"
+            - name: SLASH_FACTORY_ADDRESS
+              value: "{{ .Values.customNetwork.slashFactoryAddress }}"
+            - name: FEE_ASSET_HANDLER_CONTRACT_ADDRESS
+              value: "{{ .Values.customNetwork.feeAssetHandlerContractAddress }}"
+            {{- end }}
             - name: NODE_OPTIONS
-              value: "--max-old-space-size={{ .Values.node.nodeJs.maxOldSpaceSize}}"
+              value: {{ join " " .Values.node.nodeJsOptions | quote }}
             - name: AZTEC_PORT
               value: "{{ .Values.service.httpPort }}"
             - name: AZTEC_ADMIN_PORT
@@ -125,72 +188,108 @@ spec:
               value: "1"
             - name: P2P_ENABLED
               value: "{{ .Values.service.p2p.enabled }}"
-            - name: VALIDATOR_DISABLED
-              value: {{ .Values.node.validator.enabled | quote }}
-            - name: L1_CHAIN_ID
-              value: "{{ .Values.network.l1ChainId }}"
-            - name: OTEL_RESOURCE_ATTRIBUTES
-              value: service.name={{ .Release.Name }},service.namespace={{ .Release.Namespace }},service.version={{ .Chart.AppVersion }},environment={{ .Values.environment | default "production" }}
+            - name: P2P_PORT
+              value: "{{ .Values.service.p2p.port }}"
+            - name: P2P_QUERY_FOR_IP
+              value: "true"
+            {{- if .Values.node.remoteUrl.archiver }}
+            - name: ARCHIVER_URL
+              value: {{ .Values.node.remoteUrl.archiver | quote }}
+            {{- end }}
+            {{- if .Values.node.remoteUrl.proverBroker }}
+            - name: PROVER_BROKER_URL
+              value: {{ .Values.node.remoteUrl.proverBroker | quote }}
+            {{- end }}
+            {{- if .Values.node.remoteUrl.blobSink }}
+            - name: BLOB_SINK_URL
+              value: {{ .Values.node.remoteUrl.blobSink | quote }}
+            {{- end }}
+            {{- if gt (len .Values.node.remoteUrl.proverCoordinationNodes) 0 }}
+            - name: PROVER_COORDINATION_NODE_URLS
+              value: {{ join "," .Values.node.remoteUrl.proverCoordinationNodes | quote }}
+            {{- end }}
+            {{- if gt (len .Values.node.l1ExecutionUrls) 0 }}
+            - name: ETHEREUM_HOSTS
+              value: {{ join "," .Values.node.l1ExecutionUrls | quote }}
+            {{- end }}
+            {{- if gt (len .Values.node.l1ConsensusUrls) 0 }}
+            - name: L1_CONSENSUS_HOST_URLS
+              value: {{ join "," .Values.node.l1ConsensusUrls | quote }}
+            - name: L1_CONSENSUS_HOST_API_KEYS
+              value: {{ join "," .Values.node.l1ConsensusHostApiKeys | quote }}
+            - name: L1_CONSENSUS_HOST_API_KEY_HEADERS
+              value: {{ join "," .Values.node.l1ConsensusHostApiKeyHeaders | quote }}
+            {{- end }}
+            - name: ARCHIVER_POLLING_INTERVAL_MS
+              value: "10000"
             - name: DATA_DIRECTORY
-              value: "{{ .Values.node.storage.dataDirectory }}"
+              value: {{ .Values.node.storage.dataDirectory | quote }}
             - name: DATA_STORE_MAP_SIZE_KB
-              value: "{{ .Values.node.storage.dataStoreMapSize }}"
+              value: {{ .Values.node.storage.dataStoreMapSize | quote }}
             - name: WS_DB_MAP_SIZE_KB
-              value: "{{ .Values.node.storage.worldStateMapSize }}"
+              value: {{ .Values.node.storage.worldStateMapSize | quote }}
             - name: USE_GCLOUD_LOGGING
-              value: "{{ .Values.node.metrics.useGcloudLogging }}"
+              value: {{ .Values.node.metrics.useGcloudLogging | quote }}
+            {{- if .Values.node.metrics.otelCollectorEndpoint }}
             - name: OTEL_EXCLUDE_METRICS
-              value: "{{ .Values.node.metrics.otelExcludeMetrics }}"
+              value: {{ .Values.node.metrics.otelExcludeMetrics | quote }}
             - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
               value: "{{ .Values.node.metrics.otelCollectorEndpoint }}/v1/metrics"
             - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
               value: "{{ .Values.node.metrics.otelCollectorEndpoint }}/v1/traces"
             - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
               value: "{{ .Values.node.metrics.otelCollectorEndpoint }}/v1/logs"
-            - name: SENTINEL_ENABLED
-              value: "{{ .Values.node.sentinel.enabled }}"
-            {{- if .Values.node.blobSink.enabled }}
-            - name: BLOB_SINK_URL
-              value: "{{ .Values.node.blobSink.url }}"
             {{- end }}
+            {{- if .Values.node.coinbase }}
+            - name: COINBASE
+              value: {{ .Values.node.coinbase | quote }}
+            - name: PROVER_ID
+              value: {{ .Values.node.coinbase | quote }}
+            {{- end }}
+            - name: SENTINEL_ENABLED
+              value: {{ .Values.node.sentinel.enabled | quote }}
           ports:
             - containerPort: {{ .Values.service.httpPort }}
+              name: http-rpc
             - containerPort: {{ .Values.service.admin.port }}
+              name: admin
             - containerPort: {{ .Values.service.p2p.port }}
+              name: p2p-tcp
             - containerPort: {{ .Values.service.p2p.port }}
               protocol: UDP
+              name: p2p-udp
           resources:
             {{- toYaml .Values.node.resources | nindent 12 }}
       volumes:
-        {{- if .Values.nodePortEnabled }}
+        - name: l1-publisher
+          secret:
+            secretName: {{ include "chart.name" . }}-l1-publisher
+        {{- if or .Values.service.p2p.nodePortEnabled .Values.hostNetwork }}
         - name: init-nodeport
-          configMap:
-            name: init-nodeport
-            emptyDir: {}
+          emptyDir: {}
         {{- end }}
-    {{- if not .Values.persistence.enabled }}
+  {{- if not .Values.persistence.enabled }}
         - name: storage
           emptyDir: {}
-    {{- else if .Values.persistence.existingClaim }}
+  {{- else if .Values.persistence.existingClaim }}
         - name: storage
           persistentVolumeClaim:
             claimName: {{ .Values.persistence.existingClaim }}
-    {{- else }}
-    volumeClaimTemplates:
-    - metadata:
-        name: storage
-          annotations:
-            {{- toYaml .Values.persistence.annotations | nindent 10 }}
-        spec:
-          accessModes:
-            {{- toYaml .Values.persistence.accessModes | nindent 10 }}
-          resources:
-            requests:
-              storage: {{ .Values.persistence.size | quote}}
-          storageClassName: {{ .Values.persistence.storageClassName }}
-          {{- if .Values.persistence.selector }}
-          selector:
-            {{- toYaml .Values.persistence.selector | nindent 10 }}
-          {{- end }}
-    {{- end }}
-
+  {{- else }}
+  volumeClaimTemplates:
+  - metadata:
+      name: storage
+      annotations:
+        {{- toYaml .Values.persistence.annotations | nindent 10 }}
+    spec:
+      accessModes:
+        {{- toYaml .Values.persistence.accessModes | nindent 12 }}
+      resources:
+        requests:
+          storage: {{ .Values.persistence.size | quote}}
+      storageClassName: {{ .Values.persistence.storageClassName }}
+      {{- if .Values.persistence.selector }}
+      selector:
+        {{- toYaml .Values.persistence.selector | nindent 12 }}
+      {{- end }}
+  {{- end }}
