Merge branch 'master' into md/document-macros

diff --git a/build-system/scripts/query_manifest b/build-system/scripts/query_manifest
--- a/build-system/scripts/query_manifest
+++ b/build-system/scripts/query_manifest
@@ -3,6 +3,7 @@ set -eu
 CMD=$1
 REPO=$2
 
+ROOT_PATH=${ROOT_PATH:-$PWD}
 MANIFEST=$ROOT_PATH/build_manifest.json
 
 if [ $(jq "has(\"$REPO\")" $MANIFEST) == "false" ]; then
@@ -10,36 +11,94 @@ if [ $(jq "has(\"$REPO\")" $MANIFEST) == "false" ]; then
   exit 1
 fi
 
+function get_deps {
+  local TYPE=$(jq -r ".\"$1\".dependencies | type" $MANIFEST)
+  if [ "$TYPE" == "string" ]; then
+    # Execute string as command relative to buildDir to retrieve dependencies.
+    local CMD=$BUILD_DIR/$(jq -r ".\"$1\".dependencies")
+    if [ ! -f "$CMD" ]; then
+      >&2 echo "Dependency script not found: $CMD"
+      exit 1
+    fi
+    local PROJECT_DIR=$($0 projectDir $1)
+    DEPS=($($CMD $PROJECT_DIR))
+  elif [ "$TYPE" == "null" ]; then
+    # Execute default script relative to buildDir to retrieve dependencies.
+    local CMD=$BUILD_DIR/scripts/get_dependencies.sh
+    if [ ! -f "$CMD" ]; then
+      >&2 echo "Dependency script not found: $CMD"
+      exit 1
+    fi
+    local PROJECT_DIR=$($0 projectDir $1)
+    DEPS=($($CMD $PROJECT_DIR))
+  elif [ "$TYPE" == "array" ]; then
+    DEPS=($(jq -r ".\"$1\".dependencies // [] | .[]" $MANIFEST))
+  else
+    >&2 echo "dependencies must be a array, string or null."
+    exit 1
+  fi
+}
+
+function add_rebuild_patterns {
+  local TYPE=$(jq -r ".\"$1\".rebuildPatterns | type" $MANIFEST)
+  if [ "$TYPE" == "string" ]; then
+    local FILE=$(jq -r ".\"$1\".rebuildPatterns" $MANIFEST)
+    local BUILD_DIR=$($0 buildDir $1)
+    PATTERNS=(${PATTERNS[@]} $(cat $BUILD_DIR/$FILE))
+  elif [ "$TYPE" == "array" ]; then
+    PATTERNS=(${PATTERNS[@]} $(jq -r ".\"$1\".rebuildPatterns | .[]" $MANIFEST))
+  else
+    >&2 echo "Missing rebuildPatterns property. Either filename as string, or patterns as array."
+    exit 1
+  fi
+}
+
 case "$CMD" in
   dockerfile)
-    jq -r ".\"$REPO\".dockerfile // \"Dockerfile\"" $MANIFEST
+    # In the manifest, the path is relative to buildDir. Return absolute path.
+    BUILD_DIR=$($0 buildDir $REPO)
+    DOCKERFILE=$(jq -r ".\"$REPO\".dockerfile // \"Dockerfile\"" $MANIFEST)
+    echo $BUILD_DIR/$DOCKERFILE
     ;;
   buildDir)
-    jq -r ".\"$REPO\".buildDir" $MANIFEST
+    # In the manifest, the path is relative to the repo root. Return absolute path.
+    BUILD_DIR=$(jq -r ".\"$REPO\".buildDir" $MANIFEST)
+    echo $ROOT_PATH/$BUILD_DIR
     ;;
   projectDir)
+    # In the manifest, the path is relative to the repo root. Return absolute path.
+    PROJECT_DIR=$(jq -r ".\"$REPO\".projectDir // .\"$REPO\".buildDir" $MANIFEST)
+    echo $ROOT_PATH/$PROJECT_DIR
+    ;;
+  relativeProjectDir)
     jq -r ".\"$REPO\".projectDir // .\"$REPO\".buildDir" $MANIFEST
     ;;
   dependencies)
-    ALL_DEPS=()
+    BUILD_DIR=$($0 buildDir $REPO)
+    declare -A ALL_DEPS
     add_deps() {
-      DEPS=($(jq -r ".\"$1\".dependencies // [] | .[]" $MANIFEST))
-      ALL_DEPS=(${ALL_DEPS[@]} ${DEPS[@]})
+      if [[ -v ALL_DEPS[$1] ]]; then
+        return
+      fi
+      ALL_DEPS["$1"]=1
+      get_deps $1
       for DEP in "${DEPS[@]}"; do
         add_deps $DEP
       done
     }
     add_deps $REPO
-    printf "%s\n" "${ALL_DEPS[@]}" | sort | uniq
+    for KEY in "${!ALL_DEPS[@]}"; do
+      echo $KEY
+    done | sort
     ;;
   rebuildPatterns)
-    ALL_PATTERNS=($(jq -r ".\"$REPO\".rebuildPatterns | .[]" $MANIFEST))
     DEPS=($($0 dependencies $REPO))
+    PATTERNS=()
+    add_rebuild_patterns $REPO
     for DEP in "${DEPS[@]}"; do
-      PATTERNS=($(jq -r ".\"$DEP\".rebuildPatterns | .[]" $MANIFEST))
-      ALL_PATTERNS=(${ALL_PATTERNS[@]} ${PATTERNS[@]})
+      add_rebuild_patterns $DEP
     done
-    printf "%s\n" "${ALL_PATTERNS[@]}" | sort | uniq
+    printf "%s\n" "${PATTERNS[@]}" | sort | uniq
     ;;
   submodulePath)
     DIR=$($0 buildDir $REPO)
