[ci rebuild noir]

diff --git a/build-system/scripts/setup_env b/build-system/scripts/setup_env
--- a/build-system/scripts/setup_env
+++ b/build-system/scripts/setup_env
@@ -88,6 +88,13 @@ echo export VERSION_TAG=$VERSION_TAG >> $BASH_ENV
 echo export DEPLOY_TAG=$DEPLOY_TAG >> $BASH_ENV
 echo export BRANCH=$BRANCH >> $BASH_ENV
 echo export PULL_REQUEST=$PULL_REQUEST >> $BASH_ENV
+# We want very strict failures on any failing command, undefined variable, or commands that pipe to other commands.
+echo set -euo pipefail >> $BASH_ENV
+# Enable logging if [ci debug] is in commit message.
+if [[ "$COMMIT_MESSAGE" == *"[ci debug]"* ]]; then
+  echo export BUILD_SYSTEM_DEBUG=1 >> $BASH_ENV
+  echo set -x >> $BASH_ENV
+fi
 
 # Only run the following if we're the result of a commit (i.e. not being run manually).
 if [ -n "$COMMIT_HASH" ]; then
