fix

diff --git a/ci3/cache/download b/ci3/cache/download
--- a/ci3/cache/download
+++ b/ci3/cache/download
@@ -1,9 +1,29 @@
 #!/bin/bash
-# Use ci3 script base.
-echo "This file should not outside of bootstrap/test, this may have accidentally been committed if so!"
-source "$(git rev-parse --show-toplevel)/ci3/base/source"
-if $ci3/cache/download.bkup "$@"; then
-  echo "Should not have found download $@" >> "$ci3/cache/.test_faillures"
-  exit 0
+set -eu -o pipefail
+[ "${BUILD_SYSTEM_DEBUG:-}" = 1 ] && set -x
+
+if [ "$#" -lt 1 ]; then
+  echo "Usage: $0 <tar.gz_file_to_download_and_extract>" >&2
+  exit 1
 fi
-exit 1
+
+if [ "${USE_CACHE:-0}" -lt 1 ]; then
+  # Only download if USE_CACHE is 1
+  echo "Not using cache for $1 because USE_CACHE=0."
+  exit 1
+fi
+# Get the tar.gz file name from the argument
+TAR_FILE="$1"
+OUT_DIR="${2:-.}"
+
+# Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
+if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
+  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$TAR_FILE" "-" | tar -xzf - -C "$OUT_DIR" 2>/dev/null
+else
+  # Default to AWS S3 URL if no custom endpoint is set
+  S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
+  # Attempt to download and extract the cache file
+  mkdir -p "$OUT_DIR"
+  (curl -s -f "$S3_ENDPOINT/build-cache/$TAR_FILE" | tar -xzf - -C "$OUT_DIR" 2>/dev/null) || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
+fi
+echo "Cache download and extraction of $TAR_FILE complete." >&2
