chore: ci2.5 => ci3 merge (#10349)
- build images using new bootstrap
- scripts pass
- start of earthfile
- get rid of is_test

diff --git a/ci3/cache/download b/ci3/cache/download
--- a/ci3/cache/download
+++ b/ci3/cache/download
@@ -1,41 +1,29 @@
 #!/bin/bash
-set -eu
+set -eu -o pipefail
+[ "${BUILD_SYSTEM_DEBUG:-}" = 1 ] && set -x
 
 if [ "$#" -lt 1 ]; then
   echo "Usage: $0 <tar.gz_file_to_download_and_extract>" >&2
   exit 1
 fi
 
-if [ "${USE_CACHE:-0}" -lt 1 ] ; then
+if [ "${USE_CACHE:-0}" -lt 1 ]; then
   # Only download if USE_CACHE is 1
+  echo "Not using cache for $1 because USE_CACHE=0."
   exit 1
 fi
-
 # Get the tar.gz file name from the argument
 TAR_FILE="$1"
 OUT_DIR="${2:-.}"
 
-function on_exit() {
-  # Cleanup the temporary tar.gz file
-  rm -f "$TAR_FILE"
-}
-# Run on any exit
-trap on_exit EXIT
-
+mkdir -p "$OUT_DIR"
 # Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
 if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
-  # Extract URL from S3_BUILD_CACHE_AWS_PARAMS (assumes the format "--endpoint-url <URL>")
-  # TODO stop passing with endpoint url
-  S3_ENDPOINT=$(echo "$S3_BUILD_CACHE_AWS_PARAMS" | sed -n 's/--endpoint-url \([^ ]*\)/\1/p')
+  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$TAR_FILE" "-" | tar -xzf - -C "$OUT_DIR" 2>/dev/null
 else
   # Default to AWS S3 URL if no custom endpoint is set
   S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
+  # Attempt to download and extract the cache file
+  (curl -s -f "$S3_ENDPOINT/build-cache/$TAR_FILE" | tar -xzf - -C "$OUT_DIR" 2>/dev/null) || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
 fi
-# Attempt to download the cache file
-curl -s -f -O "${S3_ENDPOINT}/build-cache/$TAR_FILE" || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
-
-# Extract the cache file
-mkdir -p "$OUT_DIR"
-tar -xzf "$TAR_FILE" -C "$OUT_DIR"
-
 echo "Cache download and extraction of $TAR_FILE complete." >&2
diff --git a/ci3/cache/download_flag b/ci3/cache/download_flag
--- a/ci3/cache/download_flag
+++ b/ci3/cache/download_flag
@@ -1,4 +1,5 @@
 #!/bin/bash
+[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x
 set -eu
 
 if [ "$#" -lt 1 ]; then
@@ -7,20 +8,21 @@ if [ "$#" -lt 1 ]; then
 fi
 
 if [ "${USE_CACHE:-0}" -lt 1 ] ; then
+  # Don't look if CI isn't set. No need to muddle with dev runs.
+  echo "Running test $1 because USE_CACHE is not 1."
   exit 1
 fi
 
 NAME=$1
 
+# Read out the build flag as it has the context of the last success.
 # Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
 if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
-  # Extract URL from S3_BUILD_CACHE_AWS_PARAMS (assumes the format "--endpoint-url <URL>")
-  # TODO stop passing with endpoint url
-  S3_ENDPOINT=$(echo "$S3_BUILD_CACHE_AWS_PARAMS" | sed -n 's/--endpoint-url \([^ ]*\)/\1/p')
+  # Write the flag file to stdout, return exit success if found
+  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$NAME.flag" - --quiet --no-progress
 else
   # Default to AWS S3 URL if no custom endpoint is set
   S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
+  # Write the flag file to stdout, return exit success if found
+  curl -s -f "$S3_ENDPOINT/build-cache/$NAME.flag" -O || (echo "Running test $NAME because cache flag not found." && exit 1)
 fi
-# Attempt to download the cache file
-curl -s -f -o /dev/null "${S3_ENDPOINT}/build-cache/$NAME.flag" || (echo "Flag $NAME not found." && exit 1)
-echo "Flag $NAME exists."
diff --git a/ci3/cache/upload b/ci3/cache/upload
--- a/ci3/cache/upload
+++ b/ci3/cache/upload
@@ -1,4 +1,5 @@
 #!/bin/bash
+[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x
 set -eu
 
 if [ "$#" -lt 2 ]; then
@@ -8,25 +9,17 @@ fi
 
 # Name, intended to have .tar.gz ending
 name="$1"
-
+# Now $@ = our binary path args
 shift 1
 
-tar_dir=$(mktemp -d)
-tar_file="$tar_dir/${name}"
-
-function on_exit() {
-  # Cleanup the temporary folder
-  rm -rf "$tar_dir"
-}
-trap on_exit EXIT
-
-# Create the tar.gz file
-# Rest of args are our binary paths
-tar -czf "$tar_file" $@
-
-if ! aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 ls "s3://aztec-ci-artifacts/build-cache/$name" >/dev/null 2>&1; then
-  aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 cp "$tar_file" "s3://aztec-ci-artifacts/build-cache/$name" >&2
+if aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 ls "s3://aztec-ci-artifacts/build-cache/$name" >/dev/null 2>&1; then
+  echo "Skipping upload, already exists: $name" >&2
+  exit 0
+fi
+# Pipe tar directly to AWS S3 cp
+if tar -czf - "$@" | aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 cp - "s3://aztec-ci-artifacts/build-cache/$name" >&2 ; then
   echo "Cache upload of $name complete." >&2
 else
-  echo "Skipping upload, already exists: $name" >&2
+  echo "Cache upload of $name failed." >&2
+  exit 0
 fi
