fixes

diff --git a/ci3/cache/download b/ci3/cache/download
--- a/ci3/cache/download
+++ b/ci3/cache/download
@@ -1,8 +1,39 @@
 #!/bin/bash
-# Use ci3 script base.
-source "$(git rev-parse --show-toplevel)/ci3/base/source"
-if ! $ci3/cache/download.bkup "$@"; then
-  echo "Should have found download $@" >> "$ci3/cache/.test_faillures"
+set -eu
+[ "${BUILD_SYSTEM_DEBUG:-}" = 1 ] && set -x
+
+if [ "$#" -lt 1 ]; then
+  echo "Usage: $0 <tar.gz_file_to_download_and_extract>"
   exit 1
 fi
-exit 0
+
+if [ "${USE_CACHE:-0}" -lt 1 ]; then
+  # Only download if USE_CACHE is 1
+  exit 1
+fi
+# Get the tar.gz file name from the argument
+TAR_FILE="$1"
+OUT_DIR="${2:-.}"
+
+function on_exit() {
+  # Cleanup the temporary tar.gz file
+  rm -f "$TAR_FILE"
+}
+# Run on any exit
+trap on_exit EXIT
+
+# Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
+if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
+  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$TAR_FILE" "$TAR_FILE"
+else
+  # Default to AWS S3 URL if no custom endpoint is set
+  S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
+  # Attempt to download the cache file
+  curl -s -f -O "$S3_ENDPOINT/build-cache/$TAR_FILE" || (echo "Cache download of $TAR_FILE failed." && exit 1)
+fi
+
+# Extract the cache fileA
+mkdir -p "$OUT_DIR"
+tar -xzf "$TAR_FILE" -C "$OUT_DIR"
+
+echo "Cache download and extraction of $TAR_FILE complete."
