clean up diff

diff --git a/ci3/cache/download b/ci3/cache/download
--- a/ci3/cache/download
+++ b/ci3/cache/download
@@ -1,8 +1,8 @@
 #!/bin/bash
 # Use ci3 script base.
 source "$(git rev-parse --show-toplevel)/ci3/base/source"
-if $ci3/cache/download.bkup "$@"; then
-  echo "Should not have found download $@" >> "$ci3/cache/.test_faillures"
-  exit 0
+if ! $ci3/cache/download.bkup "$@"; then
+  echo "Should have found download $@" >> "$ci3/cache/.test_faillures"
+  exit 1
 fi
-exit 1
+exit 0
