remove temporaries

diff --git a/ci3/cache/download b/ci3/cache/download
--- a/ci3/cache/download
+++ b/ci3/cache/download
@@ -28,12 +28,9 @@ if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
 else
   # Default to AWS S3 URL if no custom endpoint is set
   S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
-  # Attempt to download the cache file
-  curl -s -f -O "$S3_ENDPOINT/build-cache/$TAR_FILE" || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
+  # Attempt to download and extract the cache file
+  mkdir -p "$OUT_DIR"
+  (curl -s -f -O "$S3_ENDPOINT/build-cache/$TAR_FILE" | tar -xzf - -C "$OUT_DIR") || (echo "Cache download of $TAR_FILE failed." >&2 && exit 1)
 fi
-
-# Extract the cache file
-mkdir -p "$OUT_DIR"
-tar -xzf "$TAR_FILE" -C "$OUT_DIR"
 
 echo "Cache download and extraction of $TAR_FILE complete." >&2
diff --git a/ci3/cache/download_flag b/ci3/cache/download_flag
--- a/ci3/cache/download_flag
+++ b/ci3/cache/download_flag
@@ -16,13 +16,11 @@ NAME=$1
 
 # Extract endpoint URL if S3_BUILD_CACHE_AWS_PARAMS is set
 if [[ -n "${S3_BUILD_CACHE_AWS_PARAMS:-}" ]]; then
-  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$NAME.flag" "$NAME.flag" --quiet --no-progress
+  # Write the flag file to stdout, return exit success if found
+  aws $S3_BUILD_CACHE_AWS_PARAMS s3 cp "s3://aztec-ci-artifacts/build-cache/$NAME.flag" - --quiet --no-progress
 else
   # Default to AWS S3 URL if no custom endpoint is set
   S3_ENDPOINT="http://aztec-ci-artifacts.s3.amazonaws.com"
-  # Attempt to download the cache file
-  curl -s -f -O "$S3_ENDPOINT/build-cache/$NAME.flag" || (echo "Flag $NAME not found." && exit 1)
+  # Write the flag file to stdout, return exit success if found
+  curl -s -f || (echo "Flag $NAME not found." && exit 1)
 fi
-
-rm $NAME.flag
-echo "Flag $NAME exists."
