Test for bootstrap.sh

diff --git a/ci3/cache/has_flag b/ci3/cache/has_flag
--- a/ci3/cache/has_flag
+++ b/ci3/cache/has_flag
@@ -1,4 +1,9 @@
-# Are we able to download from S3 a file with the flag name?
 #!/bin/bash
-RUN_FLAG=$1
-! $(dirname $0)/download_flag "$RUN_FLAG"
+echo "HELL YA"
+# Use ci3 script base.
+source "$(git rev-parse --show-toplevel)/ci3/base/source"
+if ! $ci3/cache/has_flag.bkup "$@"; then
+  echo "Should not want to skip $@" >> "$ci3/cache/.test_faillures"
+fi
+# We never return true, as we don't want to run tests
+exit 1
