remove temporaries

diff --git a/ci3/cache/upload b/ci3/cache/upload
--- a/ci3/cache/upload
+++ b/ci3/cache/upload
@@ -17,19 +17,10 @@ NAME="$1"
 
 shift 1
 
-TAR_DIR=$(mktemp -d)
-TAR_FILE="$TAR_DIR/${NAME}"
-
-function on_exit() {
-  # Cleanup the temporary folder
-  rm -rf "$TAR_DIR"
-}
-trap on_exit EXIT
-
-# Create the tar.gz file
-# Rest of args are our binary paths
-tar -czf "$TAR_FILE" $@
-
-if aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 cp "$TAR_FILE" "s3://aztec-ci-artifacts/build-cache/$NAME" >&2 ; then
+# Pipe tar directly to AWS S3 cp
+if tar -czf - "$@" | aws ${S3_BUILD_CACHE_AWS_PARAMS:-} s3 cp - "s3://aztec-ci-artifacts/build-cache/$NAME" >&2 ; then
   echo "Cache upload of $NAME complete." >&2
+else
+  echo "Cache upload of $NAME failed." >&2
+  exit 1
 fi
