test pass

diff --git a/scripts/tests/bootstrap/test b/scripts/tests/bootstrap/test
--- a/scripts/tests/bootstrap/test
+++ b/scripts/tests/bootstrap/test
@@ -2,7 +2,7 @@
 # Use the minio script base. We ensure minio is running and wipe it.
 source $(git rev-parse --show-toplevel)/ci3/cache/test_source
 
-# export DENOISE=${DENOISE:-1}
+export DENOISE=${DENOISE:-1}
 # Tests the various modes of bootstrap test usage.
 # We wrap and mock ci3/cache/should_run to detect when a test tries to run.
 # We never return true, as we don't actually want to run tests here.
@@ -81,15 +81,15 @@ PROJECTS=(
 
 for project in "${PROJECTS[@]}"; do
   # Run the tests
-  echo "$project test_CI_0"
-  test_CI_0 $project | sed "s/^/$project test_CI_0: /" || (echo "$project test_CI_0 failure" && exit 1)
-  echo "$project test_CI_0 success"
-  echo "$project test_CI_1 pass 1"
-  test_CI_1_first_pass $project | sed "s/^/$project test_CI_1 pass 1: /" || (echo "$project test_CI_0 failure" && exit 1)
-  echo "$project test_CI_1 pass 1 success"
-  echo "$project test_CI_1 pass 2"
-  test_CI_1_second_pass $project | sed "s/^/$project test_CI_0 pass 2: /" || (echo "$project test_CI_0 failure" && exit 1)
-  echo "$project test_CI_1 pass 2 success"
+  echo "$project 1/3: CI=0 and all tests try to run"
+  test_CI_0 $project | sed "s/^/$project 1/3: /" || (echo "$project 1/3 failure" && exit 1)
+  echo "$project 1/3"
+  echo "$project 2/3: CI=1 and all tests try to run, downloads fail"
+  test_CI_1_first_pass $project | sed "s/^/$project 2/3: /" || (echo "$project 2/3 failure" && exit 1)
+  echo "$project 2/3 success"
+  echo "$project 3/3: CI=1 and all tests do not run, downloads work"
+  test_CI_1_second_pass $project | sed "s/^/$project 3/3: /" || (echo "$project 3/3 failure" && exit 1)
+  echo "$project 3/3 success"
 done
 
 echo "All tests passed successfully."
