denoise

diff --git a/scripts/tests/bootstrap/test b/scripts/tests/bootstrap/test
--- a/scripts/tests/bootstrap/test
+++ b/scripts/tests/bootstrap/test
@@ -82,13 +82,13 @@ PROJECTS=(
 for project in "${PROJECTS[@]}"; do
   # Run the tests
   echo "$project 1/3: CI=0 and all tests try to run"
-  test_CI_0 $project | sed "s/^/$project 1/3: /" || (echo "$project 1/3 failure" && exit 1)
+  test_CI_0 $project | sed "s/^/$project 1\/3: /" || (echo "$project 1/3 failure" && exit 1)
   echo "$project 1/3"
   echo "$project 2/3: CI=1 and all tests try to run, downloads fail"
-  test_CI_1_first_pass $project | sed "s/^/$project 2/3: /" || (echo "$project 2/3 failure" && exit 1)
+  test_CI_1_first_pass $project | sed "s/^/$project 2\/3: /" || (echo "$project 2/3 failure" && exit 1)
   echo "$project 2/3 success"
   echo "$project 3/3: CI=1 and all tests do not run, downloads work"
-  test_CI_1_second_pass $project | sed "s/^/$project 3/3: /" || (echo "$project 3/3 failure" && exit 1)
+  test_CI_1_second_pass $project | sed "s/^/$project 3\/3: /" || (echo "$project 3/3 failure" && exit 1)
   echo "$project 3/3 success"
 done
 
