recover from inconsistent graph

diff --git a/scripts/earthly-cloud b/scripts/earthly-cloud
--- a/scripts/earthly-cloud
+++ b/scripts/earthly-cloud
@@ -18,4 +18,14 @@ fi
 # ensure lowercase
 USERNAME=$(echo "$USERNAME" | tr '[:upper:]' '[:lower:]')
 earthly sat --org aztec launch --size $SIZE --platform $PLATFORM $RUNNER_PREFIX-$USERNAME-$ARCH || true
-earthly -P --no-output --org aztec --remote-cache=aztecprotocol/cache:bb-native-tests --sat $RUNNER_PREFIX-$USERNAME-$ARCH $@
+# capture output to handle earthly edge cases
+earthly -P --no-output --org aztec --remote-cache=aztecprotocol/cache:bb-native-tests --sat $RUNNER_PREFIX-$USERNAME-$ARCH $@ 2>&1 | tee .output.txt >&2 || true
+# TODO potentially handle other intermittent errors here
+if grep 'failed to get edge: inconsistent graph state' .output.txt ; then
+  # TODO we need to limit earthly parallelism or sometimes get
+  # 'failed to solve: failed to get edge: inconsistent graph state'
+  # so we use arbitrary WAIT statement groups. Pending earthly support.
+  # for now we just try to recover from the failures.
+  echo "Got 'inconsistent graph state'. Restarting earthly. See https://github.com/earthly/earthly/issues/2454'
+  earthly -P --no-output --org aztec --remote-cache=aztecprotocol/cache:bb-native-tests --sat $RUNNER_PREFIX-$USERNAME-$ARCH $@ 2>&1 | tee .output.txt >&2
+fi
