bench on own runner

diff --git a/scripts/run_on_builder b/scripts/run_on_builder
--- a/scripts/run_on_builder
+++ b/scripts/run_on_builder
@@ -1,5 +1,44 @@
 #!/bin/bash
 set -eu
-# Enter repo root.
-cd $(dirname $0)/..
-exec ssh -o StrictHostKeychecking=no -i $SPOT_KEY ubuntu@$SPOT_IP "$@"
+
+# Enter the repo root
+cd "$(dirname "$0")/.."
+
+# Max number of retries
+max_retries=5
+count=0
+
+# Temporary file for error capture
+tmpfile=$(mktemp)
+
+while true; do
+  # Execute the SSH command and redirect stderr to a temp file
+  if ssh -o StrictHostKeyChecking=no -i "$SPOT_KEY" ubuntu@"$SPOT_IP" "$@" 2>"$tmpfile"; then
+    break # SSH was successful, exit loop
+  else
+    # Read the error from the temp file
+    error_msg=$(<"$tmpfile")
+
+    # Check for the specific error message
+    if [[ "$error_msg" == *"kex_exchange_identification: read: Connection reset by peer"* ]]; then
+      ((count++)) # Increment retry counter
+
+      # Check retry limit
+      if [ "$count" -eq "$max_retries" ]; then
+        echo "Reached maximum number of retries, exiting."
+        exit 1
+      fi
+
+      # Retry message and wait
+      echo "Detected SSH error to retry, retrying in 5 seconds..."
+      sleep 5
+    else
+      # Different error or no error, break loop
+      cat "$tmpfile" >&2 # Output other errors to stderr
+      break
+    fi
+  fi
+done
+
+# Clean up: Remove the temporary file
+rm -f "$tmpfile"
