handle spot evicts gracefully

diff --git a/.github/ensure-builder/action.yml b/.github/ensure-builder/action.yml
--- a/.github/ensure-builder/action.yml
+++ b/.github/ensure-builder/action.yml
@@ -3,9 +3,6 @@ name: Setup Workflow
 description: "Reusable setup steps"
 
 inputs:
-  runner_action:
-    default: start
-    required: false
   runner_type:
     required: true
   username:
@@ -59,7 +56,7 @@ runs:
       with:
         # inputs:
         runner_label: ${{ steps.select_instance.outputs.runner_label }}
-        subaction: ${{ inputs.runner_action }}
+        subaction: start
         github_token: ${{ env.GH_SELF_HOSTED_RUNNER_TOKEN }}
         aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
         aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
@@ -134,7 +131,34 @@ runs:
       with:
         run: echo $DOCKERHUB_PASSWORD | docker login -u aztecprotocolci --password-stdin
     - name: Run On Builder
-      if: ${{ inputs.run }}
-      uses: ./.github/run-on-builder
+      id: test
+      env:
+        # avoid double shell interpolation
+        RUN_SCRIPT: |
+          export GITHUB_REF_NAME=${{ github.ref_name }};
+          cd ~/run-${{ env.RUN_ID }};
+          ci3/aws_handle_evict "${{ inputs.run }}"
+      shell: bash
+      run:
+        set +e
+        scripts/run_on_builder "$RUN_SCRIPT"
+        exit_code=$!
+        echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
+        if [ $exit_code = 155 ]; then
+          echo "Spot eviction detected - retrying with on-demand."
+        fi
+
+    - name: Re-run with On-Demand
+      uses: ./.github/ensure-builder
+      if: steps.test.outputs.exit_code == '155' && inputs.spot_strategy != "None"
       with:
+        username: ${{ inputs.username }}
+        runner_type: ${{ inputs.runner_type}}
+        spot_strategy: None
         run: ${{ inputs.run }}
+
+    # If we aren't rerunning, report exit code
+    - name: Report Exit Code
+      shell: bash
+      if: steps.test.outputs.exit_code != '155' || inputs.spot_strategy == "None"
+      run: exit ${{ steps.test.outputs.exit_code }}
diff --git a/.github/ensure-tester/action.yml b/.github/ensure-tester/action.yml
--- a/.github/ensure-tester/action.yml
+++ b/.github/ensure-tester/action.yml
@@ -78,14 +78,7 @@ runs:
         ec2_subnet_id: subnet-4cfabd25
         ec2_security_group_id: sg-0ccd4e5df0dcca0c9
         ec2_key_name: "build-instance"
-        ec2_instance_tags: '[{"Key": "Keep-Alive", "Value": "true"}]'
-
-    - name: Print Startup Log
-      shell: bash
-      run:
-        # Try 6 times to see if .user-data-finished has been written to
-        for i in {0..6} ; do scripts/run_on_tester "cat /home/ubuntu/.user-data-finished" && break ; sleep 5 ; done ;
-        scripts/run_on_tester "cat /run/log.out"
+        ec2_instance_tags: '[{"Key" "Keep-Alive", "Value": "true"}]'
 
     # Set up a context for this run
     - name: Initialize Tester
@@ -123,9 +116,36 @@ runs:
       with:
         post: scripts/run_on_tester "sudo shutdown now" || true
 
-    - name: Test
-      shell: bash
+    - name: Run On Tester
+      id: test
       env:
         # avoid double shell interpolation
-        RUN_SCRIPT: export GITHUB_REF_NAME=${{ github.ref_name }} ; cd ~/run-${{ env.RUN_ID }} ; ${{ inputs.run }}
-      run: scripts/run_on_tester "$RUN_SCRIPT"
+        RUN_SCRIPT: |
+          export GITHUB_REF_NAME=${{ github.ref_name }};
+          cd ~/run-${{ env.RUN_ID }};
+          ci3/aws_handle_evict "${{ inputs.run }}"
+      shell: bash
+      run:
+        set +e
+        scripts/run_on_tester "$RUN_SCRIPT"
+        exit_code=$!
+        echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
+        if [ $exit_code = 155 ]; then
+          echo "Spot eviction detected - retrying with on-demand."
+        fi
+
+    - name: Re-run with On-Demand
+      uses: ./.github/ensure-tester
+      if: steps.test.outputs.exit_code == '155' && inputs.spot_strategy != "None"
+      with:
+        username: ${{ inputs.username }}
+        runner_type: ${{ inputs.runner_type}}
+        spot_strategy: None
+        ttl: ${{ inputs.ttl }}
+        run: ${{ inputs.run }}
+
+    # If we aren't rerunning, report exit code
+    - name: Report Exit Code
+      shell: bash
+      if: steps.test.outputs.exit_code != '155' || inputs.spot_strategy == "None"
+      run: exit ${{ steps.test.outputs.exit_code }}
