fix(ci): don't report for now on kind-network-test

diff --git a/yarn-project/end-to-end/Earthfile b/yarn-project/end-to-end/Earthfile
--- a/yarn-project/end-to-end/Earthfile
+++ b/yarn-project/end-to-end/Earthfile
@@ -300,4 +300,5 @@ kind-network-smoke:
 kind-network-transfer:
   ARG values_file
   LOCALLY
-  RUN NAMESPACE=transfer FRESH_INSTALL=true VALUES_FILE=${values_file:-default.yaml} ./scripts/network_test.sh ./src/spartan/transfer.test.ts
+  # This has || true so it does NOT report failure in github actions job. To be reenabled once stable
+  RUN NAMESPACE=transfer FRESH_INSTALL=true VALUES_FILE=${values_file:-default.yaml} ./scripts/network_test.sh ./src/spartan/transfer.test.ts || true
