chore: switch over to isolated runner

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -120,26 +120,32 @@ jobs:
               +${{ matrix.test }}
 
   acir-bench:
-    runs-on: ${{ inputs.username || github.actor }}-bench-x86
+    runs-on: ubuntu-latest
     needs: setup
     steps:
-      - {
-          uses: actions/checkout@v4,
-          with: { ref: "${{ github.event.pull_request.head.sha }}" },
-        }
+      - uses: actions/checkout@v4
+        with: { ref: "${{ env.GIT_COMMIT }}" }
       - uses: ./.github/ci-setup-action
+      - name: Setup and Test
+        uses: ./.github/ensure-tester-with-images
+        timeout-minutes: 40
         with:
-          dockerhub_password: "${{ secrets.DOCKERHUB_PASSWORD }}"
-          concurrency_key: acir-bench-${{ inputs.username || github.actor }}-bench-x86
-      - name: ACIR Proving Bench
-        working-directory: ./noir/
-        timeout-minutes: 15
-        run: |
-         ../scripts/earthly-ci -P \
+          runner_type: 16core-tester-x86
+          builder_type: builder-x86
+          # these are copied to the tester and expected by the earthly command below
+          # if they fail to copy, it will try to build them on the tester and fail
+          builder_images_to_copy: aztecprotocol/aztec:${{ env.GIT_COMMIT }}
+          # command to produce the images in case they don't exist
+          builder_command: cd noir && ../scripts/earthly-ci +barretenberg-acir-benches-bb
+          run: |
+            set -eux
+            cd ./noir/
+            export FORCE_COLOR=1
+            ../scripts/earthly-ci -P \
               --secret AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
               --secret AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
               --no-output \
-              +barretenberg-acir-benches-bb
+              +barretenberg-acir-benches-bb         
 
   bench-summary:
     needs: bench-e2e
