test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -928,64 +928,81 @@ jobs:
   #         # delete the comment in case changes no longer impact circuit sizes
   #         delete: ${{ !steps.public_functions_sizes_diff.outputs.markdown }}
   #         message: ${{ steps.public_functions_sizes_diff.outputs.markdown }}
+  test:
+    runs-on: ubuntu-20.04
+    steps:
+      - run: exit 1
+  merge-check:
+    runs-on: ubuntu-20.04
+    needs:
+      - test
+      # # must be kept in sync with rerun-check
+      # - setup
+      # - configure
+      # - build
+      # - e2e
+      # # - bench-e2e # non-blocking
+      # # - acir-bench # non-blocking
+      # # - bench-summary # non-blocking
+      # - bb-gcc
+      # - bb-native-tests
+      # - bb-js-test
+      # - noir-build-acir-tests
+      # - bb-acir-tests-bb
+      # - bb-acir-tests-bb-ultra-plonk
+      # - bb-acir-tests-bb-ultra-honk
+      # - bb-acir-tests-bb-mega-honk
+      # - bb-acir-tests-sol
+      # - bb-acir-tests-sol-honk
+      # - bb-acir-tests-bb-js
+      # - noir-format
+      # - noir-test
+      # - noir-examples
+      # - noir-packages-test
+      # - noir-projects
+      # - avm-format
+      # - yarn-project-formatting
+      # - yarn-project-test
+      # - prover-client-test
+      # - network-test
+      # - kind-network-test
+      # - l1-contracts-test
+      # - docs-preview
+      # # - bb-bench # non-blocking
+      # - boxes
+      # - boxes-test
+      # - protocol-circuits-gates-report # non-blocking
+    if: always()
+    outputs:
+      failed_jobs: ${{ steps.set_failed_jobs.outputs.failed_jobs }}
+    steps:
+      - name: Check for Failures and Set Output
+        id: set_failed_jobs
+        env:
+          # Collect failed jobs from needs
+          FAILED_JOBS_JSON: ${{ toJson(needs) }}
+        run: |
+          echo "Processing failed jobs..."
+          failed_jobs=$(echo "$FAILED_JOBS_JSON" | jq -r 'to_entries[] | select(.value.result == "failure") | .key' | paste -sd "," -)
+          echo "$failed_jobs" > .failed
+          echo "failed_jobs=$failed_jobs" >> $GITHUB_OUTPUT
 
-  # merge-check:
-  #   runs-on: ubuntu-20.04
-  #   needs:
-  #     # must be kept in sync with rerun-check
-  #     - setup
-  #     - configure
-  #     - build
-  #     - e2e
-  #     # - bench-e2e # non-blocking
-  #     # - acir-bench # non-blocking
-  #     # - bench-summary # non-blocking
-  #     - bb-gcc
-  #     - bb-native-tests
-  #     - bb-js-test
-  #     - noir-build-acir-tests
-  #     - bb-acir-tests-bb
-  #     - bb-acir-tests-bb-ultra-plonk
-  #     - bb-acir-tests-bb-ultra-honk
-  #     - bb-acir-tests-bb-mega-honk
-  #     - bb-acir-tests-sol
-  #     - bb-acir-tests-sol-honk
-  #     - bb-acir-tests-bb-js
-  #     - noir-format
-  #     - noir-test
-  #     - noir-examples
-  #     - noir-packages-test
-  #     - noir-projects
-  #     - avm-format
-  #     - yarn-project-formatting
-  #     - yarn-project-test
-  #     - prover-client-test
-  #     - network-test
-  #     - kind-network-test
-  #     - l1-contracts-test
-  #     - docs-preview
-  #     # - bb-bench # non-blocking
-  #     - boxes
-  #     - boxes-test
-  #     # - protocol-circuits-gates-report # non-blocking
-  #   if: always()
-  #   steps:
-  #     - name: Report overall success (non-draft)
-  #       if: github.event.pull_request.draft == false
-  #       env:
-  #         # We treat any skipped or failing jobs as a failure for the workflow as a whole.
-  #         FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
-  #       run: |
-  #         if [[ $FAIL == true ]]; then
-  #             echo "At least one job failed (or cancelled), merging not allowed."
-  #             exit 1
-  #         else
-  #             echo "All jobs succeeded, merge allowed."
-  #             exit 0
-  #         fi
-  #     - name: Block merge (draft)
-  #       if: github.event.pull_request.draft
-  #       run: echo "Can't merge drafts." && exit 1
+      - name: Report overall success (non-draft)
+        if: github.event.pull_request.draft == false
+        env:
+          # We treat any skipped or failing jobs as a failure for the workflow as a whole.
+          FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: |
+          if [[ $FAIL == true ]]; then
+              echo "Jobs failed: $(cat .failed), merging not allowed."
+              exit 1
+          else
+              echo "All jobs succeeded, merge allowed."
+              exit 0
+          fi
+      - name: Block merge (draft)
+        if: github.event.pull_request.draft
+        run: echo "Can't merge drafts." && exit 1
 
   # rerun-check:
   #   runs-on: ubuntu-20.04
@@ -1042,16 +1059,11 @@ jobs:
   #           gh workflow run rerun.yml -F run_id=${{ github.run_id }}
   #         fi
 
-  test:
-    runs-on: ubuntu-20.04
-    steps:
-      - run: exit 1
-  # NOTE: we only notify failures after a rerun has occurred
   notify:
-    needs:
-      - test
     runs-on: ubuntu-20.04
-    if: github.event.pull_request.draft == false && github.ref == 'refs/heads/master' && failure() && github.run_attempt >= 2
+    needs:
+      - merge-check
+    if: github.ref == 'refs/heads/master' && failure()
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -1063,12 +1075,6 @@ jobs:
           authors=$(git log -1 --pretty=format:'%an <%ae>' ${{ github.sha }})
           echo "authors=${authors}" >> $GITHUB_OUTPUT
 
-      - name: Get Failed Jobs
-        id: get_failed_jobs
-        run: |
-          failed_jobs=$(echo '${{ toJson(needs) }}' | jq -r 'to_entries[] | select(.value.result == "failure") | .key' | paste -sd "," -)
-          echo "failed_jobs=${failed_jobs}" >> $GITHUB_OUTPUT
-
       - name: Send notification to aztec3-ci channel if workflow failed on master
         uses: slackapi/slack-github-action@v1.25.0
         with:
@@ -1077,7 +1083,7 @@ jobs:
               "text": "Master Github Actions failure",
               "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
               "authors": "${{ steps.get_authors.outputs.authors }}",
-              "failed_jobs": "${{ steps.get_failed_jobs.outputs.failed_jobs }}"
+              "failed_jobs": "${{ needs.merge-check.outputs.failed_jobs }}"
             }
         env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFY_WORKFLOW_TRIGGER_URL2 }}
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFY_WORKFLOW_TRIGGER_URL }}
