chore(ci): enable gcc compilation (#6590)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -194,6 +194,23 @@ jobs:
             --secret AZTEC_BOT_COMMENTER_GITHUB_TOKEN=${{ secrets.AZTEC_BOT_GITHUB_TOKEN }} \
             +bench-comment
 
+  bb-gcc:
+    needs: setup
+    runs-on: ${{ github.event.pull_request.user.login || github.actor }}-x86
+    steps:
+      - uses: actions/checkout@v4
+        with: { ref: "${{ env.GIT_COMMIT }}" }
+      # Only allow one memory-hunger prover test to use this runner
+      - uses: ./.github/ci-setup-action
+        with:
+          # must be globally unique for build x runner
+          concurrency_key: bb-native-tests-x86
+      - name: "Ensure GCC Builds"
+        working-directory: ./barretenberg/cpp/
+        timeout-minutes: 40
+        # limit our parallelism to half our cores
+        run: earthly-ci --no-output +preset-gcc
+
   # barretenberg (prover) native and AVM (public VM) tests
   # only ran on x86 for resource reasons (memory intensive)
   bb-native-tests:
@@ -479,29 +496,40 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - setup
+      # - bench-e2e # does not block merge
+      # - bench-summary # does not block merge
       - e2e
-      - bb-native-tests
       - acir-bench
       - bb-bench
+      - bb-gcc
+      - bb-js-test
+      - bb-native-tests
       - yarn-project-formatting
       - yarn-project-test
       - prover-client-test
-      - bb-js-test
       - barretenberg-acir-tests-bb-js
       - barretenberg-acir-tests-bb
       - barretenberg-acir-tests-sol
       - noir-test
+      - noir-projects
+      - l1-contracts-test
       - noir-packages-test
+      - docs-preview
+      # - protocol-circuit-gates-report # does not block merge
     if: always()
     steps:
-      - run: |
-          failed=${{ contains(needs.*.result, 'failure') }}
-          if $failed
-          then
-            echo "At least one job failed, merging not allowed."
-            exit 1
+      - name: Report overall success
+        env:
+          # We treat any skipped or failing jobs as a failure for the workflow as a whole.
+          FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
+        run: |
+          if [[ $FAIL == true ]]; then
+              echo "At least one job failed (or skipped/cancelled), merging not allowed."
+              exit 1
+          else
+              echo "All jobs succeeded, merge allowed."
+              exit 0
           fi
-          echo "All jobs succeeded, merge allowed."
 
   notify:
     needs:
