simple deploy test CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -746,6 +746,7 @@ jobs:
       - changes
       - build
       - e2e
+      - deploy-test
       # - bench-e2e # non-blocking
       # - acir-bench # non-blocking
       # - bench-summary # non-blocking
@@ -791,6 +792,30 @@ jobs:
         if: github.event.pull_request.draft
         run: echo "Can't merge drafts." && exit 1
 
+  deploy-test:
+    needs: build
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v4
+        with: { ref: "${{ env.GIT_COMMIT }}" }
+      - uses: ./.github/ci-setup-action
+      - name: Setup and Test
+        uses: ./.github/ensure-tester-with-images
+        timeout-minutes: 45
+        with:
+          runner_type: '16core-tester-x86'
+          builder_type: builder-x86
+          # these are copied to the tester and expected by the earthly command below
+          # if they fail to copy, it will try to build them on the tester and fail
+          builder_images_to_copy: aztecprotocol/aztec:${{ env.GIT_COMMIT }} aztecprotocol/end-to-end:${{ env.GIT_COMMIT }}
+          # command to produce the images in case they don't exist
+          builder_command: scripts/earthly-ci ./yarn-project+export-e2e-test-images
+          tester_ttl: 40
+          run: |
+            set -eux
+            ./spartan/scripts/setup_local_k8s.sh
+            NAMESPACE=transfer FRESH_INSTALL=true VALUES_FILE=3-validators.yaml ./scripts/network_test.sh ./src/spartan/transfer.test.ts
+
   rerun-check:
     runs-on: ubuntu-20.04
     permissions:
@@ -801,6 +826,7 @@ jobs:
       - changes
       - build
       - e2e
+      - deploy-test
       # - bench-e2e # non-blocking
       # - acir-bench # non-blocking
       # - bench-summary # non-blocking
