fix: merge-check
This was passing on skip

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -147,8 +147,17 @@ jobs:
   merge-check:
     runs-on: ${{ github.actor }}-x86
     needs: [e2e, bb-native-tests, bb-bench]
+    if: always()  # Ensures this job runs regardless of the success or failure of dependencies.
     steps:
-      - run: echo Pull request merging now allowed.
+      - run: |
+          echo "E2E Test Status: ${{ needs.e2e.outputs.status }}"
+          echo "Native Tests Status: ${{ needs.bb-native-tests.outputs.status }}"
+          echo "Bench Tests Status: ${{ needs.bb-bench.outputs.status }}"
+          if [[ "${{ needs.e2e.outputs.status }}" != 'success' || "${{ needs.bb-native-tests.outputs.status }}" != 'success' || "${{ needs.bb-bench.outputs.status }}" != 'success' ]]; then
+            echo "Pull request merging not allowed due to failures."
+            exit 1
+          fi
+          echo "Pull request merging now allowed."
 
   notify:
     needs: [e2e, bb-native-tests, bb-bench]
