Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -722,17 +722,7 @@ jobs:
           fi
       - name: Block merge (draft)
         if: github.event.pull_request.draft
-        env:
-          # We treat any skipped or failing jobs as a failure for the workflow as a whole.
-          FAIL: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
-        run: |
-          if [[ $FAIL == true ]]; then
-              echo "At least one job failed (or cancelled), merging not allowed."
-              exit 1
-          else
-              echo "All jobs succeeded, merge allowed."
-              exit 0
-          fi
+        run: echo "Can't merge drafts." && exit 1
 
   rerun-check:
     runs-on: ubuntu-20.04
