ok we do need it to run

diff --git a/.github/workflows/ci3-external.yml b/.github/workflows/ci3-external.yml
--- a/.github/workflows/ci3-external.yml
+++ b/.github/workflows/ci3-external.yml
@@ -5,9 +5,6 @@ on:
   # For external devs. Workflow file edits won't take effect in the PR.
   pull_request_target:
     types: [opened, synchronize, reopened, ready_for_review, labeled]
-    branches:
-      - master
-      - ad/fix/ci3-workflow
 
 concurrency:
   # Only allow one run per <forked-repo>/<branch>.
@@ -47,8 +44,11 @@ jobs:
             echo "Error: External PRs can't contain CI changes (forbidden files: $forbidden_changes)."
             exit 1
           fi
-          labeled="${{contains(github.event.pull_request.labels.*.name, 'ci-external') || contains(github.event.pull_request.labels.*.name, 'ci-external-once')}}"
-          if [ "$labeled" == 'false' ]; then
+          if [ ${{ github.event.pull_request.base.ref }} != "ad/fix/ci3-workflow" ]; then
+            echo "Error: External PRs can only target master, targeted: ${{ github.event.pull_request.base.ref }}."
+            exit 1
+          fi
+          if ${{contains(github.event.pull_request.labels.*.name, 'ci-external') || contains(github.event.pull_request.labels.*.name, 'ci-external-once')}}; then
             echo "External PRs need the 'ci-external' or 'ci-external-once' labels to run."
             exit 1
           fi
