fix

diff --git a/.github/workflows/ci3.yml b/.github/workflows/ci3.yml
--- a/.github/workflows/ci3.yml
+++ b/.github/workflows/ci3.yml
@@ -36,12 +36,13 @@ jobs:
       - name: Validate External Changes
         if: github.event.pull_request.head.repo.full_name != github.repository
         run: |
+          set -opipefail
           if [ ${{contains(github.event.pull_request.labels.*.name, 'ci-external') || contains(github.event.pull_request.labels.*.name, 'ci-external-once')}} == 'false' ]; then
             echo "Error: External PRs need the 'ci-external' or 'ci-external-once' labels to run." && exit 1
           fi
           #[ ${{github.event.pull_request.base.ref}} != 'master' ] && echo "Error: External PRs can only target master as a base for safety." && exit 1
           git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
-          git diff --name-only ${{ github.event.pull_request.base.ref }} HEAD -- ci3 ci.sh | grep -q . && { echo "Error: External PRs can't contain CI changes."; exit 1; }
+          git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD -- ci3 .github ci.sh | grep -q . && { echo "Error: External PRs can't contain CI changes."; exit 1; }
           # Remove any ci-external once labels.
           gh pr edit ${{ github.event.pull_request.number }} --remove-label "ci-external-once" &>/dev/null || true
       - name: Fail If Draft
@@ -122,12 +123,13 @@ jobs:
       - name: Validate External Changes
         if: github.event.pull_request.head.repo.full_name != github.repository
         run: |
+          set -opipefail
           if [ ${{contains(github.event.pull_request.labels.*.name, 'ci-external') || contains(github.event.pull_request.labels.*.name, 'ci-external-once')}} == 'false' ]; then
             echo "Error: External PRs need the 'ci-external' or 'ci-external-once' labels to run." && exit 1
           fi
           #[ ${{github.event.pull_request.base.ref}} != 'master' ] && echo "Error: External PRs can only target master as a base for safety." && exit 1
           git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
-          git diff --name-only ${{ github.event.pull_request.base.ref }} HEAD -- ci3 ci.sh | grep -q . && { echo "Error: External PRs can't contain CI changes."; exit 1; }
+          git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD -- ci3 .github ci.sh | grep -q . && { echo "Error: External PRs can't contain CI changes."; exit 1; }
           # Remove any ci-external once labels.
           gh pr edit ${{ github.event.pull_request.number }} --remove-label "ci-external-once" &>/dev/null || true
       - name: Fail If Draft
