fixes

diff --git a/.github/workflows/ci3.yml b/.github/workflows/ci3.yml
--- a/.github/workflows/ci3.yml
+++ b/.github/workflows/ci3.yml
@@ -23,10 +23,10 @@ concurrency:
 jobs:
   ci-amd64:
     runs-on: ubuntu-latest
-    # - Only trigger on pull_request_target for forks with 'external-ci' label, and never trigger from pull_request_target if not a fork.
+    # - Only trigger on pull_request_target for forks and never trigger from pull_request_target if not a fork.
     if: >
       (github.event.repository.fork == false && github.event_name != 'pull_request_target') ||
-      (github.event.repository.fork && github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'external-ci'))
+      (github.event.repository.fork && github.event_name == 'pull_request_target')
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -36,6 +36,7 @@ jobs:
       - name: Validate External Changes
         if: github.event.repository.fork
         run: |
+          [ ${{contains(github.event.pull_request.labels.*.name, 'external-ci')}} == 'false' ] && echo "Error: External PRs need the 'external-ci' label to run." && exit 1
           git fetch https://github.com/aztecprotocol/aztec-packages ${{ github.event.pull_request.base.ref }} --depth=1
           git diff --name-only ${{ github.event.pull_request.base.ref }} HEAD ci3 ci.sh | grep -q . && { echo "Error: External PRs can't contain CI changes."; exit 1; }
       - name: Fail If Draft
@@ -101,11 +102,11 @@ jobs:
 
   ci-arm64:
     runs-on: ubuntu-latest
-    # - Only trigger on pull_request_target for forks with 'external-ci' label, and never trigger from pull_request_target if not a fork.
+    # - Only trigger on pull_request_target for forks and never trigger from pull_request_target if not a fork.
     # - Also requires the 'arm64-ci' label.
     if: >
       ( (github.event.repository.fork == false && github.event_name != 'pull_request_target') ||
-        (github.event.repository.fork && github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'external-ci'))
+        (github.event.repository.fork && github.event_name == 'pull_request_target')
       ) && contains(github.event.pull_request.labels.*.name, 'arm64-ci')
     steps:
       - name: Checkout
@@ -116,6 +117,7 @@ jobs:
       - name: Validate External Changes
         if: github.event.repository.fork
         run: |
+          [ ${{contains(github.event.pull_request.labels.*.name, 'external-ci')}} == 'false' ] && echo "Error: External PRs need the 'external-ci' label to run." && exit 1
           git fetch https://github.com/aztecprotocol/aztec-packages ${{ github.event.pull_request.base.ref }} --depth=1
           git diff --name-only ${{ github.event.pull_request.base.ref }} HEAD ci3 ci.sh | grep -q . && { echo "Error: External PRs can't contain CI changes."; exit 1; }
       - name: Fail If Draft
