fix targeting

diff --git a/.github/workflows/ci3.yml b/.github/workflows/ci3.yml
--- a/.github/workflows/ci3.yml
+++ b/.github/workflows/ci3.yml
@@ -73,7 +73,9 @@ jobs:
           if git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD -- ci3 .github ci.sh | grep -q .; then
             echo "Error: External PRs can't contain CI changes." && exit 1
           fi
-          echo ${{ github.event.pull_request.base.ref }}
+          if [ ${{ github.event.pull_request.base.ref }} != "master" ]; then
+            echo "Error: External PRs can only target master, targeted: ${{ github.event.pull_request.base.ref }}." && exit 1
+          fi
           # Remove any ci-external-once labels.
           GITHUB_TOKEN=${{ secrets.AZTEC_BOT_GITHUB_TOKEN }} gh pr edit ${{ github.event.pull_request.number }} --remove-label "ci-external-once"
 
