test

diff --git a/.github/workflows/ci3.yml b/.github/workflows/ci3.yml
--- a/.github/workflows/ci3.yml
+++ b/.github/workflows/ci3.yml
@@ -120,8 +120,8 @@ jobs:
         run: |
           [ ${{contains(github.event.pull_request.labels.*.name, 'ci-external')}} == 'false' ] && echo "Error: External PRs need the 'ci-external' label to run." && exit 1
           #[ ${{github.event.pull_request.base.ref}} != 'master' ] && echo "Error: External PRs can only target master as a base for safety." && exit 1
-          git fetch https://github.com/aztecprotocol/aztec-packages ${{ github.event.pull_request.base.ref }} --depth=1
-          git diff --name-only ${{ github.event.pull_request.base.ref }} HEAD ci3 ci.sh | grep -q . && { echo "Error: External PRs can't contain CI changes."; exit 1; }
+          git fetch ${{ github.event.pull_request.base.ref }} --depth=1
+          git diff --name-only ${{ github.event.pull_request.base.ref }} HEAD -- ci3 ci.sh | grep -q . && { echo "Error: External PRs can't contain CI changes."; exit 1; }
       - name: Fail If Draft
         if: github.event.pull_request.draft && (github.event.action != 'labeled' || github.event.label.name != 'trigger-workflow')
         run: echo "CI is not run on drafts." && exit 1
