test: nightly test that we can prove epochs

diff --git a/.github/workflows/nightly-kind-test.yml b/.github/workflows/nightly-kind-test.yml
--- a/.github/workflows/nightly-kind-test.yml
+++ b/.github/workflows/nightly-kind-test.yml
@@ -62,7 +62,7 @@ jobs:
         uses: ./.github/ensure-tester-with-images
         timeout-minutes: 90
         with:
-          runner_type: ${{ contains(matrix.test, 'prover') && '64core-tester-x86' || '16core-tester-x86' }}
+          runner_type: 16core-tester-x86
           builder_type: builder-x86
           # these are copied to the tester and expected by the earthly command below
           # if they fail to copy, it will try to build them on the tester and fail
@@ -76,10 +76,36 @@ jobs:
             export FORCE_COLOR=1
             NAMESPACE=${{ matrix.test }} FRESH_INSTALL=true VALUES_FILE="16-validators.yaml" ./scripts/network_test.sh ./src/spartan/${{ matrix.test }}.test.ts || true
 
+  proving-test:
+    needs: build
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v4
+        with: { ref: "${{ env.GIT_COMMIT }}" }
+      - uses: ./.github/ci-setup-action
+      - name: Setup and Test
+        uses: ./.github/ensure-tester-with-images
+        timeout-minutes: 90
+        with:
+          runner_type: 128core-tester-x86
+          builder_type: builder-x86
+          # these are copied to the tester and expected by the earthly command below
+          # if they fail to copy, it will try to build them on the tester and fail
+          builder_images_to_copy: aztecprotocol/aztec:${{ env.GIT_COMMIT }} aztecprotocol/end-to-end:${{ env.GIT_COMMIT }}
+          # command to produce the images in case they don't exist
+          builder_command: scripts/earthly-ci ./yarn-project+export-e2e-test-images
+          tester_ttl: 90
+          run: |
+            set -eux
+            ./spartan/scripts/setup_local_k8s.sh
+            export FORCE_COLOR=1
+            NAMESPACE=proving FRESH_INSTALL=true VALUES_FILE="1-validator-with-proving.yaml" ./scripts/network_test.sh ./src/spartan/proving.test.ts || true
+
   success-check:
     runs-on: ubuntu-20.04
     needs:
       - test
+      - proving-test
     if: always()
     steps:
       - name: Report overall success
