state fixup: before PR 2ec7c7ca75

diff --git a/.github/workflows/nightly-nextnet-deploy.yml b/.github/workflows/nightly-nextnet-deploy.yml
--- a/.github/workflows/nightly-nextnet-deploy.yml
+++ b/.github/workflows/nightly-nextnet-deploy.yml
@@ -25,8 +25,16 @@ jobs:
           # Check if tonight's tag has been published to docker hub
           current_version=$(jq -r '."."' .release-please-manifest.json)
           echo "Current version: $current_version"
-          # Format the tag as: <current_version>-nightly.<YYYYMMDD>
-          nightly_tag="${current_version}-nightly.$(date -u +%Y%m%d)-amd64"
+          # Compute the next major version. e.g. if current version is 1.2.3, next major version is 2.0.0.
+          if [[ "$current_version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+            major=$(( ${BASH_REMATCH[1]} + 1 ))
+            next_major_version="${major}.0.0"
+          else
+            echo "Error: Current version format is invalid: $current_version"
+            exit 1
+          fi
+          # Format the tag as: <next_major_version>-nightly.<YYYYMMDD>
+          nightly_tag="${next_major_version}-nightly.$(date -u +%Y%m%d)-amd64"
 
           TAGS=$(curl -s https://registry.hub.docker.com/v2/repositories/aztecprotocol/aztec/tags/$nightly_tag)
           if [[ "$TAGS" != *"not found"* ]]; then
