enforce CI consistency check

diff --git a/.github/workflows/setup-runner.yml b/.github/workflows/setup-runner.yml
--- a/.github/workflows/setup-runner.yml
+++ b/.github/workflows/setup-runner.yml
@@ -62,21 +62,27 @@ jobs:
         with:
           ref: ${{ github.event.pull_request.head.sha }}
 
+      - name: Checkout Merge Pipeline Files
+        uses: actions/checkout@v4
+        # Only check PRs for consistency (not master)
+        if: ${{ github.event.pull_request.head.sha != '' }}
+        with:
+          path: merge-commit-pipeline-files  # Optional: Check out to a subdirectory
+          sparse-paths: |
+            .github/workflows/ci.yml
+            .github/workflows/setup-runner.yml
+
       - name: Ensure CI Consistency
-        # Only check PRs
+        # Only check PRs for consistency (not master)
         if: ${{ github.event.pull_request.head.sha != '' }}
         run: |
-          # Fetch the reference CI configuration files
-          curl -o reference_ci.yml https://github.com/AztecProtocol/aztec-packages/blob/master/.github/workflows/ci.yml
-          curl -o reference_setup_runner.yml https://github.com/AztecProtocol/aztec-packages/blob/master/.github/workflows/setup-runner.yml
-
           # Compare the checked-out CI configuration files with the reference files
-          if ! diff .github/workflows/ci.yml reference_ci.yml; then
-            echo "Error: CI configuration does not match the reference."
+          if ! diff .github/workflows/ci.yml merge-commit-pipeline-files/.github/workflows/ci.yml; then
+            echo "Error: ci.yml changes in master (or PR base). Please merge these changes."
             exit 1
           fi
-          if ! diff .github/workflows/setup-runner.yml reference_setup_runner.yml; then
-            echo "Error: Setup runner configuration does not match the reference."
+          if ! diff .github/workflows/setup-runner.yml merge-commit-pipeline-files/.github/workflows/ci.yml; then
+            echo "Error: setup-runner.yml changes in master (or PR base). Please merge these changes."
             exit 1
           fi
 
